Jééj!  Cirkus.
Milujem cirkus!
Je desivı, strašnı, odpornı a pripravenı ma znovu udrie.
`len pre zamestnancov`
Haló?
Je tu niekto?
HALÓÓ???
Chlapèe, vieš, e sa v tmavıch prázdnych ulièkách, ako je táto, stávajú ¾uïom zlé veci?
V túto noènú hodinu sa tu nikto neprechádza, aby sa mu nieèo nestalo.
Oh skutoène?  To je zaujímavé.  No, tak dovidenia.
Tie si tu nieèo zaèul?
Áno, a hlavne sa to stáva ¾uïom, ktorí ve¾a donášajú na inıch za ich chrbtom.
Preèo sa zrazu tak ponáh¾aš?
Nie.
Take mi budeš venova trochu pozornosti, eh?
Rád by som vedel tvoje meno.
Som Guybrush Threepwood, a som desivı pirát.
Som Guybrush Threepwood, a práve som prišiel.
Som Guybrush Threepwood, a práve odchádzam.
Poèúvaj, Peepwood—
Threepwood!
Guybrush Threepwood!
Nech sa voláš ako chceš, poèúvaj:
Som tu šerif.
Šerif Fester Shinetop.
Pamätaj si, toto je zlı èas na návštevu nášho ostrova.
Ve¾mi ZLİ èas.
Dám ti skvelú radu, nájdi si iné miesto na dovolenku.
Niekde, kde je bezpeènejšie.
Chlapèe, cítim sa ove¾a lepšie s vedomím, e je tu takı zástupca zákona.
Útulnı.
Na èo?
Hodím ich tam všetky.
Mohol by som to uvari, ale u by mi to bolo naniè.
Nechcem to spáli.
Naèo nám to bude?
Nechcem sa zamieša medzi piráta a jeho grog.
Nechcem sa zamieša medzi piráta a jeho grog.
Nie, vïaka. Neznášam obchodníkov.
Nie, vïaka. Neznášam obchodníkov.
Vyzerá znièene...
Radšej ho nechám tak.
Vyzerá znièene...
Radšej ho nechám tak.
Grrrrrr.
Vyzerá šastne, pokia¾ má svoju kostièku.
Nie je múdre budi spiaceho piráta.
Nie je múdre budi spiaceho piráta.
Sú zaraní do rozprávania piráta na¾avo.
Radšej ich nebudem ruši.
Sú zaraní do rozprávania piráta na¾avo.
Vyzerajú, e majú dos práce.
Vyzerajú, e majú dos práce.
Nie je múdre budi spiaceho piráta.
Nie je múdre budi spiaceho piráta.
Nemyslím si, e to teraz nieèo udrí.
Vyzerá to ako cínová kanvica.
Nemyslím si, e to teraz nieèo udrí.
Vyzerá to ako cínová kanvica.
Nemyslím si, e to teraz nieèo udrí.
Vyzerá to ako cínová kanvica.
Nemyslím si, e to teraz nieèo udrí.
Vyzerá to ako cínová kanvica.
Nemyslím si, e to teraz nieèo udrí.
Vyzerá to ako cínová kanvica.
Hej!
Do kuchyne môem ís len ja!
Hej!
Nelez do tej kuchyne!
Hm, u si poèul o troch pirátskych skúškach...
Áno, videli sme to.
Nu, nie si ty náhodu ten chlapec, èo sa chce sta pirátom.
Ako sa ti darí?
Ako sa ti darí, šermiar?
Ako sa ti darí, zlodej?
Ako sa ti darí, zlatokop?
Vitaj, mladı priate¾.
U si porazil Majsterku šermu?
U si ukradol sošku?
U si našiel poklad?
Hm, u si poèul o troch pirátskych skúškach...
Èo by si rád, chlapèe?
Chcem vás všetkıch zabi!
Chcem sa sta pirátom.
Chcem sa sta hasièom.
A èo ako?
Preèo otravuješ nás?
Pozri, po tej aférke s LeChuckom sme bezmocní.
A èo?
iadny pirát znamená iadny lup, a iadny lup znamená iadny grog, a my sme na grogu nebezpeène závislí...
Hmm...
Dokáeš aspoò nieèo?
Dokáem zadra dych na 10 minút!
No...
to je fajn, ale KECANÍM s nami sa pirátom nestaneš.
Budeš musie zdola...
Tri skúšky!
Tri skúšky!
Tri skúšky!
Er...
Aké sú tie tri skúšky?
Sú to skúšky, ktoré musí splni kadı pirát.
Musíš zvládnu šerm...
...potom vedie kradnú...
...a tie h¾ada.
A èo?
Predsa poklad!
Správne.
Musíš uspie v tıchto troch oblastiach:
šerm, kradnutie, a, er, h¾adanie pokladu;
potom sa vrá s dôkazom, e si to zvládol.
Potom to zapijeme grogom!!
GROG!!!
GROG!!! 
GROG!!!
Stra sa chlapèe, otravuješ nás.
Povedzte mi nieèo viac o šermovaní.
Povedzte mi ešte raz o šermovaní.
Som najstrašnejší zabijak, èo kedy mával meèom!
Povedzte mi viac o tom, ako sa sta zlodejom.
Povedzte mi ešte raz, ako ukradnú sošku.
Som najlepší stopár na tıchto ostrovoch!
Povedzte mi viac o stratenom poklade.
Povedzte mi ešte raz o stratenom poklade.
Našiel som váš 'Stratenı poklad'.
Ste smrad¾avá banda prasiat ch¾astajúcich grog!
Mimochodom, èo obsahuje grog, èo pijete?
Tak ja pôjdem.
Najskôr si kúp meè.
Musíš nájs a porazi Majsterku meèa.
Niekto v meste ti mono poradí.
Oh!
Nájdi si niekoho, kto a bude trénova.
Ha ha.
Dokáem si predstavi, ako bojuješ s Majsterkou meèa bez poriadneho tréningu!
Har Har Har
Har Har Har
Har Har Har
Najskôr zaèni trénova.
Musíš nám prinies jednu malú vec...
Sošku mnohıch rúk...
...zo sídla guvernérky!
Guvernérka má sošku vo vitríne v svojom sídle za mestom. Nie je ¾ahké sa tam dosta.
Samozrejme, e sa budeš musie dosta cez stráe.
Najzáludnejšia èas bude, ako sa dosta cez stráiace psy.
Sú to krvilaèní kríenci pudla...
...môeš sa ich pokúsi otrávi.
Legenda hovorí, e poklad je zakopanı niekde tu na ostrove...
Všetko, èo musíš urobi, je nájs legendárny poklad ostrova Mêlée™ a prinies ho sem.
Nemal by som ma mapu?
ako nájdeš poklad bez mapy!
...a nezabudni:
to miesto je oznaèené X!
Har Har Har
Har Har Har
Har Har Har
Take si porazil Majsterku meèa, je to tak?
Si silnı chlapík!
To štılové trièko si nechaj, máme ich dos.
Ah, Soška mnohıch rúk!
Si statoènı chlapec!
A ïakujeme ti, e si to pre nás ukradol.
Našiel si stratenı poklad?
Si bystrı chlapec!
To trièko si nechaj, máme ich dos.
Aby si sa stal pirátom, tak musíš smrdie a ch¾asta grog ako my.
Grog je tajnı mix, ktorı obsahuje jednu alebo viac následujúcich poloiek:
petrolej
propylén glykol
umelé sladidlá
kyselinu sírovú
rum
acetón
èervené farbivo è.2
penu
koloma
kyselinu z akumulátora
a/alebo feferónky
Ako si samozrejme dokáeš predstavi, je to jedna z najeravejších a najprchavejších látok, èo ¾udstvo pozná.
Preiera sa skrz tieto dbány tak rıchlo, e ich kuchár nestíha meni. Zrejme budú z nejakého lacného materiálu.
Har Har Har
Har Har Har
Har Har Har
Nechaj nás tu s našim grogom.
Zastav na neskôr a daj nám vedie, ako si uspel.
Bojhaf! Haf.
Barhaf, haf?
*èuch*  *èuch*
Arf-farf...
...haf?
A-uuuuuuu!
Grrrrrrrrr.
Grrrrr.
Haf
Arf.
Raf.
Grrrrrr.
HAF?
Ahaff haf!
haf ARF!
...arf?
raf, a-raf arf!
GRRRRRRRRRR!!!
haf-haf arf haf...
...bojhaf, ostrov Mêlée™!
...a-raf wuf:
...LeChuck!
Grrrrrrr!
Wurf
A-RAF!!
Waf, 'LeChuck?'
Yip!  Yip!  Yip!
Waf, waf.
A-raf?
Raff.
Grrrrrrrr!
Waf waf waf raf-raf...
Wr-raf waf?
Raf arf-arf, lup-raf...
...guvernérka Marleyová!
A-UUUUUUU! A-UUUUUUU!
(raf raf raf)
Baf-ruu waf rawwf—
—Arraaaf—
—LeChuck!
GRRRRRRRRR!
Arf, uuf-uuf, Ostrov opíc™!
*èuch*  *èuch*
Stará f¾aša.
Nepotrebujem ju.
Stará f¾aša.
Nepotrebujem ju.
Je tam správa!
Nieèo sa tu píše...
Hmm.
Vyzerá to ako legálèina.
Nedokáem to preloi.
Úbohı exemplár masovo vyrábaného turistického suveníru.
Na spodku je napísané: 'vyrobené Citrónovou hlavou'.
Pochybujem, e bude tá èaèka niekomu chıba.
A máš to, ty lacnı odpad.
A máš to, ty lacnı odpad.
Nepochybne druhá najväèšia opièia hlava, akú som kedy videl!
Nie je tu miesto, kam to strèi.
Druhé najväèšie ucho, aké som kedy videl...
...a tie najšpinavšie.
Fuj.
Vyzerá to ako nejaká svätá soška.
Na zobratie to je príliš aké...
nechám to napospas tomuto bohom zabudnutému ostrovu.
Na premiestnenie sú príliš aké.
Okrem toho, preèo by som mal tak hlúpo narúša túto svätú modlitebnú pôdu patriacu ¾udorútskym lovcom lebiek.
Vyzerám snáï ako hlodavec?
NIKTO NEPREJDE!!
Ah!  Èervenı sleï!!
Prejdi.
Ako sa opovauješ ma uráa tak úbohou èiastkou?
Urèite to pritiahne pozornos...
...a je to bezcenné...
...ale nie je to to, èo chcem.
Toto je úplne naniè.
A nie je to to, èo chcem.
Chcem nieèo také, èo dokáe odvráti pozornos od vecí, ktoré sú SKUTOÈNE dôleité.
A èo nieèo slanšie?
Ako tak na teba èakám, tak dostávam hlad.
A èo tak nieèo zjes?
Myslím, e zaklopem.
Bude to zdvorilejšie.
Nikto neodpovedá.
Èo chceš, ty vychudnutı malièky slabošskı èerv?
Èo chceš?
Oh, to si ty.
Mohli by ste ma trénova, aby som bol lepší ne Majsterka šermu?
Mohli by ste zo mòa spravi najlepšieho šermiara na Mêlée?
Mohli by sme ís dovnútra?  Je tu trochu chladno.
Nevieš, kde Majsterka šermu ije?
Um...  Mohli by ste, prosím, zahasi tú cigaretu?
Èo si hovoril?
Povedal som, e je tu trochu chladno!
Hmmm...
Máš pravdu.  Mohl by som nachladnú.
Zabudni na to, chlapèe.
Odsekla by ti hlavu raz dva.
Pokia¾ avšak neprejdeš základnym tréningom...
Nie je to dobré pre vaše zdravie a strašne to páchne.
Istee, rád ju zahasím...
...na tvojom ksichte!
Uh...
...mono radšej pôjdem.
Dobrı nápad.
Myslíš, ak nerátame Majsterku šermu?
Nie, vrátane všetkıch.  Chcem by NAJLEPŠÍ.
Lepší ne Majsterka šermu?
Ty?
Ha ha ha!
Nebudeš nikdy ani z polovice tak dobrı ako je Karla.
Ani po hodinách akej driny potiacej krv.
Pamätám si boj, bok po boku s Karlou v Port Royale...
...miestna polícia nás natlaèila do rohu!
Vyzeralo to, e je s nami amen, ale ona potom povedala—
-ale to u odboèujem...
Neváiš si to, èo máš.
Váim si to, èo mám!
Váim!
Myslím, e máš pravdu.
Viete èo, skutoène by ste mali presta fajèi.
Neváiš!
Èo by som mal naozaj urobi, je donúti a to pekne vyra.
Cítim v tebe bojovného ducha.  Urobím, èo môem.
Samozrejme...
...a to bude nieèo stá.
Videl si moju cedu¾u?
Normálne úètujem 30 zlatiek za tak ve¾kú prácu ako je táto.
Èo máš?
Èo ešte máš?
Mám 30 zlatiek.
Myslel som, e to urobíte zadarmo.
Myslím, e poèkám.  Aj tak ïakujem.
Všetko èo mám, je toto màtve kurèa.
U niè nehovor, u niè nehovor.
No, myslel si zle.
Dobre, tak stoj ty slabošská škvrna pavúèieho hlienu.
Nie je to jedno z tıch gumovıch kurèiat s ve¾kou kovovou kladkou uprostred, však e nie?
U jedno mám.
Uká mi meè.
OK, sledujte.
Myslím, e som si ho zabudol kúpi.
Nechcem ti ho ukáza.
Mám toto màtvo vyzerajúce kurèa.
Áno, naozaj pekné.
Tak do toho.
Navrhujem ti pohnú svojim zadkom do obchodu a nejakı kúpi.
Nemám vo zvyku poièiava meèe študentom.
Áno, mávanie gumovım kurèaom s ve¾kou eleznou kladkou môe by trochu nebezpeèné...
...ALE NIE JE TO MEÈ!!!
Rob ako myslíš.
Mohol by si by lepší.
OK, páchnuci èerv...
...preèo nevytiahneš ten svoj meè a neukáeš mi, èo s ním dokáeš.
Chlapèe!
Bojuješ ako sedliak s vidlami!
Zvyèajne sa nezaoberám s takou háveïou ako si ty.
Ale keï sa pozriem na tú vec s LeChuckom, ako tu kazí obchody, tak nemám na vıber...
...Potrebujem peniaze.
Áno...
...Vidím, e toto bude potrebova nejakı špeciálny prístup.
Chcem, aby si to vedel...
...Nerobím to pre kadého.
Je to len preto, e cítim to zvláštne...
...študentsko/uèite¾sko/zlatkovské puto...
...ktoré chcem rozvinú.
Teraz a postavím proti...
...STROJU.
Stroj?
Bude to bolie?
Au!
Poï blišie.  Neboj sa, nemôeš mi ublíi.
O nieko¾ko hodín neskôr...
Zaèínaš sa do toho dostáva.
O viac hodín neskôr...
Celkom to ujde.  Máš dobrú formu.
Teraz ti dovolím nazrie do skutoèného tajomstva šermu.
Šerm je ako milovanie so enou.
Nie je to o tom, èo robíš, ale èo u toho hovoríš.
Kadı blbı pirát dokáe máva nabrúsenım kusom eleza okolo seba a dúfa, e nieèo odsekne...
...ale profíci...
...vedia, e keï oslabia protivníka nejakou urákou...
...bude to pre neho ove¾a väèšia potupa.
Vidíš, chlapèe, tvoj dôvtip musí by dvakrát ostrejší ne tvoj meè.
Skúsme si pár uráok, dobre?
Okej...
...predstav si:
Bojujeme v hroznej búrke...
...presne ako to bolo s Karlou v nešastnom Port Royale.
Náhle prichádza pauza v boji a ja ti hovorím...
...'Bojuješ ako sedliak s vidlami!'
Ako odpovieš?
Oh fakt!?
Presne ako tvoja mama.
Ja som pán, a ty môj pes...
S niekım si si ma splietol, ja nie som sedliak.
Vidím, e tu máme ešte dos práce.
No, mal by si odpoveda štılom ako je tento...
...'To sedí.  Bojuješ ako ranené te¾a!'
Vidíš...
Je to ultraostrá uráka, ktorá vyhráva boje.
Skúsme ïalšiu.
Predstav si:
Si zatlaèenı k stene...
...môj meè a dvakrát sekne do tváre.
Vravím...
...'Èoskoro budeš zdobi môj meè ako ranièi!'
Ako odpovieš?
Oh fakt!?
Presne ako tvoja mama.
Ja som pán, a ty môj pes...
To sedí.  Bojuješ zase ako ranené te¾a!
Vidím, e máme vány problém.
Nie! Nie! Nie!
Takto si odpovedal predtım.
Nedáva to zmysel, keï to pouiješ teraz!
<sigh>
Správna odpoveï na...
...'Èoskoro budeš zdobi môj meè ako ranièi!'...
...môe by nieèo ako...
...'Najskôr by si s tım musel presta máva ako s prachovkou.'
Chápeš...
...ultra-ostré!
Teraz ti navrhujem vypadnú a nauèi sa vonku zopár ïalších uráok.
Nemôem si pomôc, ale cítim sa, ako by ma niekto okradol.
Som si istı, e sa cítiš podobne.
Postup, úder, krytie, odrazenie, útok.
Sleduj prácu nôh.
Nie!  Najskôr úder, potom vıpad!
Poui svoje prednosti, pred svojimi slabosami.
Odstup, dr si odstup!
...ak tu je nejaká osoba s námietkou, preèo by títo dvaja...
...er...
...¾udia nemali by spojení do zväzku manelského...
...nech prehovorí teraz, alebo nech mlèí naveky.
Tento eních nie je dentlmen!
Tento eních nie je èlovek!
Elaine!
ZASTAVTE SVADBU!!
Hej!! Kto si..?
Myslím, e sa tam nieèo deje.
Tí blázniví Špagetoví bratia sú stále vnútri.
Aha, toto poslúi ako helma!
OZVENA
ozvena
Chytrák!
Darebák!
Lotor!
Pätolízaè!
Nanièhodník!
Nièomník!
Zmätkár!
Vymletá hlava!
Šišatá hlava!
Polovièná hlava!
Syrová hlava!
Netvor!
Èo?
Vlez do toho kanónu!
Tvoje matka si oblieka vojenské spodky!
Našu mamu z toho vynechaj!  Vlez do toho kanónu!
Si kurèa!
Si màtve kurèa!
No, si màtve kurèa s kladkou uprostred!
Èo?
Len si vlez do toho kanónu.
Nie, VLEZ si do neho ty!
Nie, VLEZ si do neho ty!
Základnı postup je správny.
Potrebuje to len trochu dosmerova.
Teraz to skúsim ja!
Nie, teraz to skúsim ja!
Nie, ja!
Nie, JA!
Flákaè!
Chudák!
Surovec!
Frajer!
Vleziem si do kanónu, ale pušnı prach ma núti kıcha.
No, ja to urobi nemôem, zranil som si ruku, keï som trénoval levy.
Myslím si, e to malé škrabnutie sa vôbec nedá porovna s mojou chronickou alergiou.  Vlez do kanónu.
Nemáš iadnu alergiu, ty klamár.  Vlez do toho kanónu TY.
Nie, vlez do kanónu TY!
Nie, vlez do kanónu TY!
Flákaè!
Chudák!
Surovec!
Frajer!
. . .ahem. . .
Máte tu záchody?
Predávam tieto skvelé vesty.
Môem si poièa trampolínu?
Chlapi, preèo ste obleèení do takıch smiešnych šiat?
Opä zdravím.
Si pripravenı na kanónové èíslo?
Povedz nám, synak, chcel by si dosta šancu—
—Neopakovate¾nú—
—Zahra si v ohromnej šou—
—V smr berúcej šou—
—Dobre, nie tak smr berúcej, skutoène—
—V nebezpeènej šou—
—Nie, nie tak nebezpeènej—
—V ¾ahkej šou—
—Ale vzrušujúcej!—
—S ohromnımi—
—Dobrodrunımi, akrobatickımi—
—A preslávenımi—
—Jedineènımi, lietajúcimi—
—bratmi Fettuciniovcami!
To sme my.
Môj brat Alfredo...
...a môj brat Bill.
Znie to dobre?
Dobre.
Je to ve¾mi jednoduché, skutoène.
Vidíš ten kanón tamto?
Všetko, èo musíš urobi—
—Je vliez do kanónu—
—A my a z neho vystrelíme—
—Cez celú miestnos—
—Je to bezpeèné—
—Tak, èo hovoríš?
OK, urobím to.
Ko¾ko mi zaplatíte?
Zabudnite na to!
Zaplatíme ti 478 zlatiek.
A èo tak 478 zlatiek?
OK, to znie dobre.
V iadnom prípade!
Máš helmu?
Er... nie, nemám helmu.  Budem nejakú potrebova?
Samozrejme, e mám helmu.  Za akého idiota ma máte?
Dobre, tak si ju nasaï.
Chceme si by istí—
—e je to bezpeèné—
—Nechceme, aby si sa zranil—
—Nie, pane!
iadna helma?
Oh, musíš ma helmu—
—Nemôeš robi kanónové èíslo bez helmy—
—Nie, pane!
Zaobstaraj si helmu a potom môeme urobi kanónové èíslo.
Tak a môeme zaèa.
Postav sa tamto, synak.
Teraz si nasaï helmu—
—vlez do kanónu—
—a my sa postaráme o zvyšok.
Funguje to!
Nemôem tomu uveri!
Hej...
Si v poriadku?
?amam ajom iS  .nibboB moS
?umleh mám edK
Som Bobbin.  Si moja mama?
Kde mám helmu?
Je v poriadku!
Huráá!  Sme ušetrení zahanbujúceho a finanène zaaujúceho súdneho procesu!
Tu máte peniaze, pane.
Len malá odmena, e si nám pomohol.
{verb:local_1}
To nie je helma.
To nie je helma.
Po ïalšom zbesilom veslovaní...
Èo sa stalo, ty starı oran?
Kde sú všetci piráti?
Nalej mi!
Oh, všetci práve drancujú sídlo guvernérky.
Ako môeš myslie na ch¾ast v takejto chvíli?
Guvernérka je preè!
LeChuck a jeho posádka duchov ju zajali!
Uniesli ju na svoju loï duchov a vyparili sa preè!
Znamenala pre mòa ve¾a...
...vdy mi dokázala napísa potvrdenie pre VšZP...
...za malé všimné, samozrejme.
Èo sa stane s mojou krèmou? Oh, boe môj.
Èo sa dá urobi pre jej záchranu?
Musíš si kúpi loï a ís za òou!
Pirátsky brloh duchov je na Ostrove opíc™, to vedia všetci.
(nepıtaj sa ma ako...)
Musíš nájs spôsob, ako sa tam dosta.
Preèo by som to mal robi?
Kde mám zohna loï?
Ideš do toho so mnou?
Správne!  Zvládnem to sám!
Nalej mi!
Preèo? Pre lásku, chlapèe!
Nepopieraj to, máš to napísané na tvári.
LÁSKA
Kde? Na Stanovom vrakovisku lodí\nako kadı inı.
Povedz mu, e som a poslal ja, sme starí priatelia.
Er. . .do èerta, nemôem vypláva na more.
Mám staré zranenie z vojny.
Som si istı, e to chápeš.
Ve¾a šastia!
Nezabudni si obliec rukavice.
A nos vdy teplé ponoky.
A nezbudni napísa.
Ve¾a šastia.
U jeden máš.
Nalej si sám.
Je to desivé, a ïalej ís nehodlám.
Nie sú tu iadne banány.
Aby som sa dostal na dno priepasti, potrebujem dos dlhı povraz.
Skúsim to s touto vetvou.
Dve veslá.
Zviaza to nepôjde.
Vyzerá pevne.
Vyzerá pevne.
Èo to tam dole len je?
Práve ako ten na druhej strane.
Práve ako ten na druhej strane.
Krik¾avé, ale v povzbudzujúcom zmysle slova.
Nemyslím si, e sa s tım niekam dostanem.
Hmmm...  Myslím, e by ma to mohlo unies...
Dos ošúchanı.
Vau!  Funguje to obojsmerne.
To je ale kurèa.
Ty!
Prišiel som ti prekazi svadbu s guvernérkou Marleyovou.
Prosím, nezabíjaj ma.
Máš to zapár, ty hmlistá voodoo háveï!
Práve som si spomenul, e mám rezerváciu u svojho zubára.
A ako to plánuješ urobi?
Daj mi jedinı dôvod, preèo by som a nemal zabi.
Zapár èo?  Snaíš sa ma zastraši?
Budeš ju potrebova, a ti jednu strelím!
Guvernérka!
Guvernérka!
Guvernérka?
O èo tu ide?
Oh, Guybrush, ty šialenı osol!
Váim si to, e si ma prišiel zachráni, ale to skutoène nebolo nutné.
Mala som všetko pevne vo svojich rukách.
Bohuia¾, kvôli tvojmu príjazdu som to musela trochu urıchli.
Ako si dokázala utiec?
Myslel som, e si a LeChuck vezme.
Ak ty stojíš tu, tak kto je pod závojom?
...ako...
...kto...
...ale...
...èo...
...Ja...
...um...
Oh, to bolo jednoduché.
LeChuck je idiot,
Hej!
a väèšina z jeho posádky boli moji priatelia, keï ešte boli naive.
Áno, ja tie!
Áno, on tie!
Ale pripravila som malé prekvapenie, a by prišiel èas pobozka nevestu.
Èo?
Nevystraš ich!
Majú môj koreòovı rozpúšaè duchov!
Oh, dostanem to!
...hups...
Peknı pokus, Guybrush.
Teraz ich budem musie prenásledova, aby som ten rozpúšaè dostala naspä.
...ale...
...Ja...
...er...
...hej...
Ako si dovo¾uješ sem prís a ruši ma!
Nemôem uveri, akı si drzı!
No a ja nemôem uveri tomu, akı si hlúpy.
Musel som ti prekazi svadbu s guvernérkou Marleyovou.
Prosím, nezabíjaj ma.
Ochutnaj toto, ty prieh¾adná voodoo háveï!
Práve som si spomenul, e mám rezerváciu u svojho zubára.
Fakt?
No, nemôem uveri tvojej povrchnosti.
No, nemôem uveri tvojej pohyblivosti.
No, nemôem uveri tvojej slabosti.
No, nemôem uveri tvojej ohavnosti.
No, nemôem uveri tvojej krutosti.
No, nemôem uveri tvojej vrtkosti.
No, nemôem uveri tvojej munosti.
No, nemôem uveri tvojej elegancii.
No, nemôem uveri tvojej sile.
Ešte si ju vezmem!
Ako ma chceš zastavi?
Utlèiem a gumovım kurèaom.
Postriekam a mojim koreòovım pivom.
Dám ti úplatok za tvoju nevestu.
Pouijem svoju kopiju a kúzelnú helmu.
Musim ís, zle som zaparkoval.
Hah!
Koris pre moju krásku, eh?
Skúšali to mnohí a za svoju odvahu zomreli.
Povedz mi jedinı dôvod, preèo by som a nemal zabi.
To by nebolo pekné.
Som opásanı vıbušninou, pokia¾ by ma chcel niekto zabi.
Mám enu a tri deti.
Aká bude vıhovorka teraz, eh?
To som poèul!
Huh?
Som z teba unavenı.
Nikdy neohrozujem slušnıch, hmotnıch pirátov, ty nafúknutı mech plnı h...
...h...
...nieèoho, èo zaèína na `h`!
Uh...
...tak to poèkaj, kamarát...
...Len som si robil srandu, vieš?
...Môeme to urovna ako dentlmeni...
Oh, nie!
Je to celé ZNIÈENÉ!
Muselo se mi to pokrèi vo vrecku.
Er...
...tak hovor...
...a neunáhli sa...
Nazvané `Ako si da nohy na stôl pri h¾adaní pokladu.`
Nazvané `Ako si da nohy na stôl pri h¾adaní pokladu.`
Nazvané `Ako si da nohy na stôl pri h¾adaní pokladu.`
Nazvané `Ako sa zlepši v navigácii.`
Nazvané `Ako sa zlepši v navigácii.`
Nazvané `Ako sa zlepši v navigácii.`
Nazvané `Ako sa ozbroji pre boj na mori.`
Nazvané `Ako sa ozbroji pre boj na mori.`
Nazvané `Ako sa ozbroji pre boj na mori.`
Je hroznı, šialenı a chce ma udrie znovu.
Upozornenie pirátom na Mêlée:
Vaša guvernérka je naive, zdravá a po mojom boku, ako si vdy elala.
Ak sa nás pokúsite nájs, stretnete sa iba s hroznou skazou.
S úctou, kapitán LeChuck.
Hej!  Je skvelé, e si sa ukázal.
Poèas tej doby, èo som tu stál a èakal na teba, ma u desa ¾udí prehováralo, aby som predal tohto miláèika.
Ale povedal som, 'V IADNOM PRÍPADE.'
'Poznám chlapíka, ktorı sa do lode priamo zamiloval, a zlomilo by mu to srdce.'
Mám pravdu?
Samozrejme, e mám!
Len sa na òu pozri!
Uhladená...
...aerodynamická...
...sviná, neodolate¾ná kráska.
Myslím, e prichádza ten pravı moment.
Rozmyslel som si to.
Nemôem sa jej vzda.
Môeš dosta svoje peniaze spä.
Ako môem preda nieèo tak rozkošné?
Tak znova, dohoda je dohoda, správne?
Správne.
Odchytím a neskôr.
Ve¾a šastia.
Ui si to.
Nie som tu.
Hups!  Skoro som ti zabudol da túto námornícku literatúru.
Darèek pre teba.  Len si pamätaj, od koho ju máš.
OD STANA!!!
Mono som si mal poveda o predåenie záruky, teraz keï to vidím.
Hej, dlho sme sa nevideli.
Otis!  U som si myslel, e a u nikdy neuvidím!
Ty malı falošnı kretén!  Podviedol si ma.
Prišiel si, aby si bol v mojej posádke?
Tvoja teta Tillie peèie hnusnı mrkvovı koláè.
Oh, no tak.  Nebuï tak zlı.
Som tu, aby som pomohol.  Nielen pre peniaze.
Hej, nikdy by som neodmietol šancu na rıchlo zarobené peniaze.
Peniaze?
Hej, zaplatíš nám za to, však e?
Chlapèe, staviaš sa k tomu nepekne.
Som rád, e si to stihla, Karla.
Je pravda, èo som poèul o tebe a tom obchodníkovi?
To sedí.  Ty zase bojuješ ako ranené te¾a!
Nikdy si nevedel, kedy to poui.
Pozri, nezaèínaj si so mnou, okej?
Èo je tamto za potápajúci sa vrak?
Ako dostaneme našu loï cez tú kopu harabúrd, èo je v ceste?
Kde je nosiè?
Potrebujem ho, aby šiel naspä a vzal mi batoinu.
O èo tu ide?
Kde je naša loï?
Kde je naša posádka?
Toto nebude také jednoduché, ako som si myslel.
No, nebolo to také aké.
Jediné, èo teraz potrebujem urobi, je vytrepa ryby z nohavíc.
Jediné, èo teraz potrebujem urobi, je ukáza túto sošku vodcom pirátov a—
Ty iješ!
Guvernérka!
Hej, vy viete rozpráva!
Kto by to bol povedal?
Èo tu robíte?
Prišli ste dokonèi prácu?
Nie, prišla som vám zachráni ivot.
To nebol môj rozkaz, aby a tam Fester hodil.
Prišli ste sem, aby ste ma zachránili?
Nikdy by som si nepomyslel, e ma máte tak rada.
No, naša prvá schôdzka bola trochu trápna...
Vyzeralo to, e máte trochu problém s formovaním viet.
Ale to má väèšina tunajších obèanov.
Ale ja nie som iadny z vašich obèanov...
...Som len tulák, nikto, zdanlivı pirát.
Koho by zaujímalo, alebo by mal staros o to, èi ste ma tu nechali utopi?
Ja ju mám, Guybrush.
Oh, guvernérka...
Oh, Threepwood...
Oh, Elaine!
Oh, Guybrush!
Láska moja!
Cukríèek!
Medová bábika!
Zajaèik!
Pobozkaj ma!
Nie!  Nesmieme!
Èo?
Tu nie, tu nás všetci uvidia.
Preèo?  Hanbíš sa za mòa?
Nie, nie, to vôbec nie...
Je to len preto, e si na mòa robí nároky mnoho pirátov.
A ja tım nechcem nikoho rani, vdy im hovorím, e môj otec mi zakázal sa zamilova do piráta.
Ak nás spolu uvidia, budú vedie, e som klamala.
Tak dobre, pôjdeme do tvojho sídla.
Okej.
Ale najskôr by si mal dokonèi tie skúšky.
Nechcem, aby si bol...
...roztritı.
Ale...
Mám náhle silnı pocit, e tie skúšky musím splni...
...neodkladne.
Èo to bolo?
Som takı zmätenı.
Hej!  Èo tu tak stojíš?
Guvernérka bola unesená!
Èo?  Kım?
LeChuck ju uniesol na svoju loï.
Chytil ju, keï prišla sem, aby a zachránila.
Obávam sa, e sme ju videli naposledy.
A kde si bol po celı ten èas?  Spal si?
Kam s òou odplával?
Preèo si myslíš, e u ju nikdy neuvidíme?
Pôjdem zohna loï, posádku, a vyplávame ju zachráni!
Hej, ja som pozorovate¾, nie bodyguard.
Nebude to také jednoduché, vieš.
LeChuck uniesol guvernérku Marleyovú do svojho úkrytu na Ostrove opíc™.
Mám strach, e tu na ostrove nie je iadny pirát takı statoènı, aby ho tam prenásledoval.
Ale, hej, ve¾a šastia.
Oh, skoro som zabudol...
Nechali tu list.
Tu ti ho dávam, ale asi sa ti nebude páèi, èo je v òom napísané.
Oh, guvernérka...
Preèo si pre mòa riskovala svoj ivot?
Mono si o mòa mala väèší strach, ne som si myslel...
...Práve takı, akı ja mám teraz o teba.
Je to moje chyba, e je guvernérka v akostiach a prisahám, e ju z toho dostanem...
Aj keby som mal na Ostrov opíc™ pláva sám, aby som ju našiel!
Huch!
Hej!
Poèkaj chví¾ku!
Môem vám ponúknu koreòové pivo, pane?
Predávam túto luxusnú ústnu vodu.
Chceš vidie peknı trik?
Skús TOTO, hnusnı prízrak!
Koreòové pivo?
Oh, chlapèe!
Milujem koreòové pivo!
Je mentolová?
Mám rád len mentolovú.
Ber to èert, áno!
Milujem triky!
Vyèaruješ mi holubièku?
Predsa len, nenašiel by sa èerstvo uvarenı grog?
Prima!
Skvelé!
Kostol je opaènım smerom!
{verb:local_1}
Vyzerá ako staré opustené táborisko.
Aká pekná rastlina.
Desivé.
Sú neobyèajne svetlolté.
Po celom lese sú rovnaké zvädnuté èervené kvety.
U jeden mám.
Nemyslím si, e ponevieranie sa po lese a zbieranie kvetov je to najlepšie na to, aby som sa stal pirátom.
Obyèajnı starı peò.
`NEBEZPEÈENSTVO:  Otvorená roklina.`
Vyzerá ako obyèajnı starı peò s rovnakımi èervenımi kvetmi, aké rastú po celom lese.
Nevkroèím do toho lesného bludiska bez mapy, príruèky alebo nieèoho takého.
Je to iarivo ltá farba.
Nevkroèím do toho lesného bludiska bez mapy, príruèky alebo nieèoho takého.
S papagájom my som si pokecal lepšie.
Nejde to otvori.
Toto robi nebudem.
Niè zvláštne na tom nevidím.
Nemôem to zobra.
Odtia¾to na to nedoèiahnem.
Nedá sa to poui.
Tento dbán sa u poui nedá.
S prázdnym dbánom tu niè nezmôem.
Hej, skvelé, pitie!
Som fakt smädnı.
Huuuch!
Hups.
Vau.
Keï si spomeniem, e som to kedysi pil...
Som vo¾nı!
Oh hej, vïaka.
Ciciak!!
HA HA HA!!!
Ale...
Platí stále naša dohoda?
Som si istı, e sa vráti...
Dal mi slovo piráta.
Oh skvelé, ozaj skvelé.
Zachráò potkana a nechaj ma tu zhni.
Si skutoène ¾udomil, chlapèe.
Môj právnik mal pravdu...
Mal by som sa sta donášaèom.
Zachránim a, Elaine, s¾ubujem.
Je to môj sladkı králièek.
U chápem, preèo sa do nej LeChuck zamiloval tak rıchlo.
U chápem, preèo sa do nej piráti zamilovali tak rıchlo.
Znovuzvolenie guvernérky Marleyovej.
`Keï je len jeden kandidát, je len jedna monos.`
...a nie, nie som háklivı.
NAOZAJ by som ho chcel zjes!
Tak do toho!
Ale spomeò si na svoje problémy so ilami!
My SME kanibali, pre KRISTA!
To hej, ale i kanibali si musia strái mnostvo nenasıtenıch tukov, ako kadı inı.
Ak budem musie jes toto ovocie ešte raz, tak sa mi hlava zmení na citrón!
iadne námietky, Citrónová hlava.
Rád a vidím, synak.
Ako sa darí lodi?
Ak máš záujem si nieèo kúpi, dám ti skvelú ponuku.
Tak ako, partner.
Vieš, ako sa tak na teba pozerám, povedal by som, e si pán sveta.
Chlap s okom pre kvalitu.
Chlap, ktorı vycíti skvelı obchod, ktorı
Medzitım…
Hlboko pod Ostrovom opíc™ je zakotvená temná loï duchov piráta LeChucka.
Kapitán LeChuck...pane...ja...
Ah...
Nemôe by niè lepšie, ne diablov dych vanúci do tvojej tváre.
Nie, pane...
Niè lepšie...
Ah...
Pane...
Ja...
V dòoch ako tento si šastnı, e si màtvy.
Oh, áno pane...by màtvy je skvelé...
Si rád, e si màtvy, VŠAK?
Oh áno, pane.
Cítim sa šastnı, e ste sa objavili, prepadli moju loï, potom zavradili mòa a všetkıch na lodi...
...áno, pane...
šastnı.
To rád poèujem.
No, a èo si tu chcel?
Ah...áno, pane...no, viete, máme malı problém na ostrove Mêlée™.
PROBLÉM?!?
Akı problém sa tam asi môe vyskytova!?
Kvôli mne sú tam tí piráti z mora takí vydesení, e sa boja i vykúpa!
No...
Vyzerá to, e do mesta dorazil novı pirát.
Vlastne, skôr sa ešte len chce sta pirátom.
Mladı.
Neskúsenı.
Pravdepodobne sa nie je èoho bá.
Vôbec nechápem, preèo som vás s tım otravoval.
Pôjdem na Mêlée™ a postarám sa oòho sám.
Poèkaj!
Postarám sa o to osobne.
Moje plány sú príliš dôleité na to, aby ich skazili amatéri.
Áno, pane.
Nie som geológ, ale súdiac pod¾a tıchto konchoidálnych úlomkov...
...by som povedal, e je to kúsok kremeòa!
Ako som povedal, je to kremeò.
Keï u som v tom, pozriem sa na tento list.
Kremeò funguje najlepšie s nieèím kovovım.
Nechcem oslepnú!
Oh, iste.  Smerom k slnku.
Tento kremeò si vezmem.
Tento kameò si tie vezmem.
Tento kremeò si vezmem.
Tento kameò si tie vezmem.
Chlapèe, je tu pekne HORÚCO.
Je tu príliš šero.
Dobrá, silná vec.
VAROVANIE:
Objekty v ïalekoh¾ade sa javia vzdialenejšie, ne v skutoènosti.
S tymto vyzera moja noha väèšia.
Vnútri je pekná šošovka.
Nie je sa na èo pozera.
Je to hrdzavé.
To asi fungova nebude.
Èierne a explodujúce, presne ako to mám rád.
Sú v nej tri diery.
Èierne a explodujúce, presne ako to mám rád.
U mám dos.
Stopa tu konèí.
Hej, peknı ïalekoh¾ad.  Vyzerá rovnako ako —
Povedz, kde JE môj ïalekoh¾ad?
Oh, perfektné
Som preè pä minút a niekto si pokojne príde a rozš¾ape všetok pušnı prach po celej podlahe.
Samozrejme, e si nemyslím, e s tım máš nieèo spoloèné.
Iste to je náhoda, e si sa sem prišiel zakráda hneï potom, èo nejaká ZÁHADNÁ osoba zašpinila moju nádhernú podlahu.
Ahoj!
Vôbec mi nevadí, naozaj, e si sa nahrnul do môjho domu bez toho, aby si sa obaoval zaklopa.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Úbohé kurèatá...
Radšej nie.  Urèite tu sú pripravené pre sadistickı pohanskı rituál, a nechcel by som ho skazi.
Nie, vïaka.  U ste niekedy poèuli o salmonelóze?
Úbohé kurèatá...
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Jééj, som zvedavı, èo je v tıch košoch.
Vlastne ma to ani tak nezaujíma.
Asi jedovaté hady.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Hmmm... Vnútri je nieèo poèu.
Nie, vïaka.  Nieèo by mohlo vyskoèi a pohrız ma.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Jééj, som zvedavı, èo je v tıch košoch.
Vlastne ma to ani tak nezaujíma.
Asi jedovaté hady.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Pozrime sa, pohár plnı nakladanıch netopierov...
...je tu napísané `Triedená ve¾kos`...
...mixér plnı opièieho mäsa...
...a maèacích labiek.
Maèacie labky?!?
Aké barbarské!
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Vyzerá pohodlne, v strašidelnom zmysle slova.
Nie, vïaka.  Nezaspím na cudzom mieste.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Najskôr je vnútri telo.
Hmmm...
Gumové kurèa s kladkou uprostred...
Na èo by som to mohol poui?
Myslím, e to nebude nikomu chıba...
Som si istı, e sa niekde uplatní, ale na toto to nie je.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Chudáèik...
Nech u to bolo èoko¾vek.
Nie, vïaka.  Radšej sa nebudem dotıka tıchto desivıch voodoo vecí.
Toto je tesárovo majstrovské dielo.
Nechcem.  Mám z toho husiu kou.
S èím ti môem pomôc, synak?
Áno?
Volám sa Guybrush Threepwood a som hrôzostrašnı pirát.
Ko¾ko stojí toto úboho vyzerajúce kurèa?
Dokáeš èíta z ruky?  Budem bohatı?
Myslím, e u nechcem o mojej budúcnosti viac vedie... to staèí.
Cesta?  O akej ceste hovoríš?
Máte to tu útulné.  Myslím, e u pôjdem.
Poèkaj...
...niè nehovor.
Poznám tvoje meno...
...si...
...Guybrush...
...Guybrush Nosochlp.
Nie...
...Threepwood.
Guybrush Threepwood.
Mám pravdu?
Vau!  To je ohromné.  Poznáš ešte nejaké triky?
Náhoda.
Nerobím iadne triky.
Ja poznám pravdu.
Polovica ¾udí èo poznám sa volá Guybrush.
Neboj sa otvori svoju myse¾.  Pomôe ti to na tvojej budúcej ceste.
Ahhh...
Cítim tu narastajúci pocit viny za kráde môjho kurèaa.
Vezmi si ho.
Je tvoje.
Preèo to nechceš?
Je to prekliate starodávnou voodoo kliatbou?
Nie...
...kladka škrípe.
Tak...
...moje dokonalé schopnosti mi hovoria, e a zaujíma tvoja budúcnos.
Si na òu pripravenı?
Áno!  Povedz mi všetko.
Nie!  Niè mi nehovor.  ivot má by nevıpoèitate¾nı a vzrušujúci.
Rob ako myslíš.
Povedzme, e ma u unavuješ.
Odíï, prosím.
Vidím, e si zmenil názor.
Cesta?  O akej ceste hovoríš?
Myslela som, e nechceš pozna svoju budúcnos.
Zmenil si názor?
U nieèo vidím...
...Vidím dlhú plavbu, dlhú plavbu.
Vidím a, ako velíš lodi.
Fakt!
Vidím...
Èo?
Vidíš èo?
Vidím obrovskú opicu.
Asi King Kong!
Vidím a vo vnútri tej opice.
Odporné.
Poèkaj...
...u sa to vyjasòuje.
Tvoja cesta má ve¾a èastí.
Uvidíš veci, ktoré by si radšej nevidel.
Budeš poèu veci, ktoré by si radšej nepoèul.
Budeš sa uèi veci, ktoré by si nikdy nechcel vedie.
Aké veci?
Neznášam prekvapenia.
NIE!
Teraz nie je ten správny èas.
A si uvedomíš svoje poslanie, tak sa zastav...
...Potom ti to poviem.
Huch!
Nemyslím si, e sa vráti.
Haló?
Hej! Som spä a pripravenı dozvedie sa o svojej budúcnosti.
Asi by som u mal odís.
Asi tu nikto nie je.
Huch!
Prišiel si zisti viac o svojej budúcnosti?
Áno, musím rıchlo nájs guvernérku.
Viete o nieèom, èo mi pomôe?
Vidím nieko¾ko ïalších, èo ti pomáhajú na tvojej ceste.
Najskôr ich nájdi, budeš ich potrebova.
Nenávidím to blıskanie, potom vkuse vidím mihajúce škvrny.
Ticho!
Prichádza ïalšie videnie.
Musíš...
Musím èo?
Musíš ís na Ostrov opíc™.
A tam budeš, nájdeš ducha piráta LeChucka.
Ukrıva sa hlboko...
...hlboko pod Ostrovom opíc™.
Existuje len jedna dostatoène silná vec na znièenie ducha piráta LeChucka.
Aká?
Je to starodávny koreò.
Ak sa dobre pripraví, dokáe znièi ducha jednım dotykom.
Sila!
Vidím toho viac...
...ove¾a viac.
Vyklop to!
Vidím kanibalov ijúcich na ostrove.
Oni...
...ti pomáhajú...
...alebo a poierajú?...
...Nemôem to presne urèi, videnie je trochu rozmazané.
Skvelé.
Teraz be a nájdi tú, ktorá a miluje.
Ale buï opatrnı...
Bez obáv, budem dáva bacha na LeChucka.
Nie na LeChucka,...  ale na seba a to èo príde.
Èo zistíš o sebe a o všetkom okolo teba.
Poznamená a to.
Nepoznám toho mua, ale toho psa som videl v bare.
Nepoznám toho mua, ale má skvelı klobúk.
Bezcenná váza!
Nie je èas na èítanie.
Nie je èas na èítanie.
Nie je èas na èítanie.
Nie je èas na èítanie.
Vnútri som zamkol šerifa!
To je nádhera.
Stále nemám pilník.
Naspä sa u nevrátim!
Musím si da pozor, aby som sa neporezal.
Musím si da pozor, aby som sa neporezal.
Musím si da pozor, aby som sa neporezal.
Musím si da pozor, aby som sa neporezal.
Musím si da pozor, aby som sa neporezal.
Je tu napísané: `S tımto sa k tebe hlodavce ani nepriblíia.`
Sú to asi nejaké náboenské kecy.
Sú pokrèené a pokryté hnusnım slizom.  Práve teraz nemám chu to u, odporné.
Sú pokrèené a pokryté hnusnım slizom.  Práve teraz nemám chu to u, odporné.
Stavím sa, e sa to bude hodi.
Nie sú to iadne sponky na odstránenie.
Budem to potrebova.
Nechám to radšej tu.
Nie!
To èervené tlaèidlo NIE!
Je to ve¾kı, hnusnı, chlpatı bizón s voskovımi perami.
Nepohnem s tım.
Nepohnem s tım.
Acck!
...hlodavce!
Je to nádherné!
Nemôem to otvori.
Uh, oh!
Whíííííííí!!
Ale ešte som s tebou neskonèil!
Uh-oh.
Myslel si si, e odtia¾to odídeš so Soškou mnohıch rúk, však?
Pozrite, môem to vysvetli...
Tak môem—
Ty si otrávil milované pudly našej guvernérky...
Oni len spia!
...vlámal si sa do jej domu...
Bolo otvorené!
...a ukradol jeden z najvzácnejších umeleckıch kúskov!
Nie, zle ste to pochopili!
Oh skutoène?
Dobre, tak si vypoèujme tvoje vysvetlenie.
Hovorila, e si to môem vzia!
Chcel som si to poièa!
Patrí to do múzea!
Vodcovia pirátov mi povedali, aby som to urobil!
Len som to chcel ís vyvetra.
Ha!
O èo tu ide?
Chytil jsem tohto chuligána, ako zdrhá s vašou soškou, guvernérka.
Hovorí, e ste mu ju dala!
To je pravda.  Dala.
Hovorí, e si ju len poièiava!
To je pravda.  Poièala som mu ju.
Hovorí, e to patrí do múzea!
To je pravda.  Patrí.
Hovorí, e ho k tomu naviedli vodcovia pirátov!
Nie je prvou osobou, ktorú zviedli z cesty!
Hovorí, e to chcel ís vyvetra.
No, nie je to od neho pekné?
Èo?
Poèuli ste ma, Fester.
Iná otázka je, ako sa sem mohol dosta, keï ste tu mali strái?
Ja... Uh...
Choïte preè, Fester.
Postarám sa o to.
Hmpf!
Nájdem si a neskôr.
Ospravedlò ho.
Je novı.
Som guvernérka Marleyová...
Musím by blázon!
Mám pilník...
To by ho malo na chví¾u zdra!
Keby som len mal pilník, mohol by som získa tú sošku!
Uf!
To bolo o chlp.
Aspoò, e mám koneène tú sošku.
Vyzerá to ako práca pre šerifa Festera!
Kam si myslíš, e ideš, Threekword?
Kam si myslíš, e ideš, Thumpwind?
Kam si myslíš, e ideš, Throotwink?
Kam si myslíš, e ideš, Throofwood?
Kam si myslíš, e ideš, Threedwork?
Kam si myslíš, e ideš, Throomwald?
Idem uloi tú sošku do bezpeèného trezora.
Vieš, nie je zase a tak neskoro zoznámi sa a sta sa priate¾mi.
Prepáète, pán Koleno, ale stojíte mi v ceste.
Uhni, Fester.
Oh naozaj?
Viem o bezpeènom trezore, do ktorého by si to mohol uloi...
do trezora Daveyho Jonesa!!!
Áno...
A tie nie je zase tak neskoro, aby som a zabil, a šiel to oslavova s kamarátmi do baru.
Potrebuješ sa upokoji.
Daj mi svoj meè.
Uh-oh.
{verb:local_1}
Asi nemá záujem.
Nie, dokia¾ nezlezie.
Vyzerá fakt hladnı.
Stále vyzerá nejakı hladnı.
Vyzerá šastne.
{verb:local_1}
Tak mi daj tu prekliatu loï.
Toto je tvoj KONIEC, budeš ra bahno!
Toto je tvoj KONIEC, budeš ra bahno!
Toto je tvoj KONIEC, budeš ra bahno!
Toto je tvoj KONIEC, budeš ra bahno!
Èoskoro budeš zdobi môj meè ako ranièi!
Èoskoro budeš zdobi môj meè ako ranièi!
Èoskoro budeš zdobi môj meè ako ranièi!
Èoskoro budeš zdobi môj meè ako ranièi!
Moja vreckovka ti vysaje všetku krv!
Moja vreckovka ti vysaje všetku krv!
Moja vreckovka ti vysaje všetku krv!
Moja vreckovka ti vysaje všetku krv!
¼udia padajú na kolená, keï ma vidia prichádza.
¼udia padajú na kolená, keï ma vidia prichádza.
¼udia padajú na kolená, keï ma vidia prichádza.
¼udia padajú na kolená, keï ma vidia prichádza.
Kedysi som mal psa, ktorı bol bystrejší, ako si ty.
Kedysi som mal psa, ktorı bol bystrejší, ako si ty.
Kedysi som mal psa, ktorı bol bystrejší, ako si ty.
Kedysi som mal psa, ktorı bol bystrejší, ako si ty.
Chce sa mi z teba zvraca.
Chce sa mi z teba zvraca.
Chce sa mi z teba zvraca.
Chce sa mi z teba zvraca.
Nikto sa nikdy netopil v mojej krvi, a nikdy ani nebude!
Nikto sa nikdy netopil v mojej krvi, a nikdy ani nebude!
Nikto sa nikdy netopil v mojej krvi, a nikdy ani nebude!
Nikto sa nikdy netopil v mojej krvi, a nikdy ani nebude!
Bojuješ ako sedliak s vidlami!
Bojuješ ako sedliak s vidlami!
Bojuješ ako sedliak s vidlami!
Bojuješ ako sedliak s vidlami!
Tú jazvu, èo mám na tvári, som získal pri krvavej bitke!
Tú jazvu, èo mám na tvári, som získal pri krvavej bitke!
Tú jazvu, èo mám na tvári, som získal pri krvavej bitke!
Tú jazvu, èo mám na tvári, som získal pri krvavej bitke!
U si prestal nosi plienky?
U si prestal nosi plienky?
U si prestal nosi plienky?
U si prestal nosi plienky?
Poèul som, e si prašivı donášaè.
Poèul som, e si prašivı donášaè.
Poèul som, e si prašivı donášaè.
Poèul som, e si prašivı donášaè.
Pre môj cvièenı mozog nie si iadny ozajstnı súper.
Pre môj cvièenı mozog nie si iadny ozajstnı súper.
Pre môj cvièenı mozog nie si iadny ozajstnı súper.
Pre môj cvièenı mozog nie si iadny ozajstnı súper.
Chováš sa ako obrák.
Chováš sa ako obrák.
Chováš sa ako obrák.
Chováš sa ako obrák.
U nehodlám poèúva tvoju drzú papu¾u!
U nehodlám poèúva tvoju drzú papu¾u!
U nehodlám poèúva tvoju drzú papu¾u!
U nehodlám poèúva tvoju drzú papu¾u!
Nemám slov na to, akı si odpornı.
Nemám slov na to, akı si odpornı.
Nemám slov na to, akı si odpornı.
Nemám slov na to, akı si odpornı.
S opicami sa mi rozprávalo lepšie, ne s tebou.
S opicami sa mi rozprávalo lepšie, ne s tebou.
S opicami sa mi rozprávalo lepšie, ne s tebou.
S opicami sa mi rozprávalo lepšie, ne s tebou.
Práve mám za sebou dlhú a ostrú lekciu, a teraz ti to ukáem.
Práve mám za sebou dlhú a ostrú lekciu, a teraz ti to ukáem.
Práve mám za sebou dlhú a ostrú lekciu, a teraz ti to ukáem.
Práve mám za sebou dlhú a ostrú lekciu, a teraz ti to ukáem.
Môj jazyk je ostrejší, ne tvoj meè.
Môj jazyk je ostrejší, ne tvoj meè.
Moje meno je postrachom v kadom zákutí tohto ostrova!
Moje meno je postrachom v kadom zákutí tohto ostrova!
Najrozumnejší nepriatelia predo mnou utekajú u pri prvom poh¾ade na mòa!
Najrozumnejší nepriatelia predo mnou utekajú u pri prvom poh¾ade na mòa!
Takého zbabelca stretneš iba raz!
Takého zbabelca stretneš iba raz!
Ak je tvoj brat ako ty, tak by sa mal oeni s prasaom.
Ak je tvoj brat ako ty, tak by sa mal oeni s prasaom.
V ivote ma nikto neuvidí bojova tak zle, ako ty.
V ivote ma nikto neuvidí bojova tak zle, ako ty.
Vymámim z tvojho tela kadú kvapku krvi!
Vymámim z tvojho tela kadú kvapku krvi!
Môj poslednı boj skonèil s krvou na mojich rukách.
Môj poslednı boj skonèil s krvou na mojich rukách.
Dúfam, e máš pripravenú loï na rıchly útek.
Dúfam, e máš pripravenú loï na rıchly útek.
Môj meè je najlepší v celom Karibiku!
Môj meè je najlepší v celom Karibiku!
Mám odvahu a zruènos majstra meèov!
Mám odvahu a zruènos majstra meèov!
Kadé slovo, èo mi hovoríš, je blbos.
Kadé slovo, èo mi hovoríš, je blbos.
Ste boles v mojom zadku, pane!
Ste boles v mojom zadku, pane!
Teraz ti u iadny pohyb nepomôe.
Teraz ti u iadny pohyb nepomôe.
Teraz u viem, èo oplzlos a blbos znamenajú.
Teraz u viem, èo oplzlos a blbos znamenajú.
¼udí ako ty vidím obyèajne lea na podlahe v krème.
¼udí ako ty vidím obyèajne lea na podlahe v krème.
Si takı škaredı!
Si takı škaredı!
Si takı škaredı!
Si takı škaredı!
Takı idiot!
Takı idiot!
Takı idiot!
Takı idiot!
Ty si hovoríš pirát!
Ty si hovoríš pirát!
Ty si hovoríš pirát!
Ty si hovoríš pirát!
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Ale ja som ti na to našiel u vhodné miesto.  CHÁPEŠ?
Ale ja som ti na to našiel u vhodné miesto.  CHÁPEŠ?
Ale ja som ti na to našiel u vhodné miesto.  CHÁPEŠ?
Ale ja som ti na to našiel u vhodné miesto.  CHÁPEŠ?
Ale ja som ti na to našiel u vhodné miesto.  CHÁPEŠ?
Najskôr s tım prestaò máva ako s prachovkou.
Najskôr s tım prestaò máva ako s prachovkou.
Najskôr s tım prestaò máva ako s prachovkou.
Najskôr s tım prestaò máva ako s prachovkou.
Najskôr s tım prestaò máva ako s prachovkou.
Take teraz robíš hlavného domovníka.
Take teraz robíš hlavného domovníka.
Take teraz robíš hlavného domovníka.
Take teraz robíš hlavného domovníka.
Take teraz robíš hlavného domovníka.
Dokonca aj predtım, ne ucítili tvoj dych?
Dokonca aj predtım, ne ucítili tvoj dych?
Dokonca aj predtım, ne ucítili tvoj dych?
Dokonca aj predtım, ne ucítili tvoj dych?
Dokonca aj predtım, ne ucítili tvoj dych?
Urèite a nauèil všetko, èo vieš.
Urèite a nauèil všetko, èo vieš.
Urèite a nauèil všetko, èo vieš.
Urèite a nauèil všetko, èo vieš.
Urèite a nauèil všetko, èo vieš.
Pred sebou vidím niekoho, kto u to urobil.
Pred sebou vidím niekoho, kto u to urobil.
Pred sebou vidím niekoho, kto u to urobil.
Pred sebou vidím niekoho, kto u to urobil.
Pred sebou vidím niekoho, kto u to urobil.
Beíš TAK rıchlo?
Beíš TAK rıchlo?
Beíš TAK rıchlo?
Beíš TAK rıchlo?
Beíš TAK rıchlo?
To sedí.  Bojuješ ako ranené te¾a!
To sedí.  Ty zase bojuješ ako ranené te¾a!
To sedí.  Ty zase bojuješ ako ranené te¾a!
To sedí.  Ty zase bojuješ ako ranené te¾a!
To sedí.  Ty zase bojuješ ako ranené te¾a!
Dúfam, e teraz u nebudeš dvíha svoj nos.
Dúfam, e teraz u nebudeš dvíha svoj nos.
Dúfam, e teraz u nebudeš dvíha svoj nos.
Dúfam, e teraz u nebudeš dvíha svoj nos.
Dúfam, e teraz u nebudeš dvíha svoj nos.
Preèo, chceš si jedny poièa?
Preèo, chceš si jedny poièa?
Preèo, chceš si jedny poièa?
Preèo, chceš si jedny poièa?
Preèo, chceš si jedny poièa?
Škoda, e a vôbec nikto nepozná.
Škoda, e a vôbec nikto nepozná.
Škoda, e a vôbec nikto nepozná.
Škoda, e a vôbec nikto nepozná.
Škoda, e a vôbec nikto nepozná.
Urèite máš problém ho poui.
Urèite máš problém ho poui.
Urèite máš problém ho poui.
Urèite máš problém ho poui.
Urèite máš problém ho poui.
Urèite sa ti bude páèi tak pohodlnı ivot.
Urèite sa ti bude páèi tak pohodlnı ivot.
Urèite sa ti bude páèi tak pohodlnı ivot.
Urèite sa ti bude páèi tak pohodlnı ivot.
Urèite sa ti bude páèi tak pohodlnı ivot.
Tvoje hemeroidy sa opä prebudili, eh?
Tvoje hemeroidy sa opä prebudili, eh?
Tvoje hemeroidy sa opä prebudili, eh?
Tvoje hemeroidy sa opä prebudili, eh?
Tvoje hemeroidy sa opä prebudili, eh?
Ale máš, len sa to bojíš poui.
Ale máš, len sa to bojíš poui.
Ale máš, len sa to bojíš poui.
Ale máš, len sa to bojíš poui.
Ale máš, len sa to bojíš poui.
Som rád, e navštevuješ svojich rodinnıch príbuznıch.
Som rád, e navštevuješ svojich rodinnıch príbuznıch.
Som rád, e navštevuješ svojich rodinnıch príbuznıch.
Som rád, e navštevuješ svojich rodinnıch príbuznıch.
Som rád, e navštevuješ svojich rodinnıch príbuznıch.
Oh áno?
Oh áno?
Oh áno?
Oh áno?
Oh áno?
Ja som pán, a ty môj pes.
Ja som pán, a ty môj pes.
Ja som pán, a ty môj pes.
Ja som pán, a ty môj pes.
Ja som pán, a ty môj pes.
U sa bojím, u sa trasiem.
U sa bojím, u sa trasiem.
U sa bojím, u sa trasiem.
U sa bojím, u sa trasiem.
U sa bojím, u sa trasiem.
Uhh... Môeš to zopakova? Nejako som to prepoèul.
Uhh... Môeš to zopakova? Nejako som to prepoèul.
Uhh... Môeš to zopakova? Nejako som to prepoèul.
Uhh... Môeš to zopakova? Nejako som to prepoèul.
Uhh... Môeš to zopakova? Nejako som to prepoèul.
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Vzdávam sa!  Vyhral si!
Tu cesta konèí, môj malı pomätenı kamarát.
Tvoje problémové dni na ostrove Mêlée™ sa skonèili.
Moje plány s guvernérkou sú ïaleko dôleitejšie...
...a som dos ïaleko k ich naplneniu na to...
...aby som riskoval, e mi bude takı pirát, ako ty, sta v ceste.
Zbohom, pán Gobrush, Vobrush alebo ako sa to vôbec voláte.
Hmmm...
Vïaka tomuto by dnešnı deò mohol by nakoniec celkom peknı.
Myslím, e zostanem na tejto strane miestnosti, je tu bezpeènejšie.
Vyzerá ako ten èudnı chlap, ktorého som videl na hornej palube.
Vyzerá ako Ostrov opíc™.
Fuj.  Nie, vïaka.
Urobil si nejaké modré melíry do fúzov.
Je to ve¾kı duchovskı k¾úè.
Nevyzerá to, e ten k¾úè tam pasuje.
Arrr...  Èo je to za hluk?
Kto sa opovauje vliez do kabíny ducha piráta LeChucka?
Vietor nerobí takı škripot!
Strachuj sa o ivot, ty, ktorı si vstúpil!
To musí by vietor.
Loï v tıchto vodách vydáva èudné zvuky.
Èudné miesta, èudnı hluk.
Mal by si sa bá.
Je to len otvor, nie sú tam dvere.
Je to len otvor, nie sú tam dvere.
Je to len otvor, nie sú tam dvere.
Je to len otvor, nie sú tam dvere.
Nejde to zavrie.
Je to f¾aša duchovského grogu.
U sú otvorené.
Radšej si to odloím.
Vyzerá, e spí.
Duchom tie smrdia nohy.
Nemôem mu to zobra.
Vyzerá ako f¾aša plná grogu.
Èo to bolo???
Mal by som ho radšej necha tak.
Hej! Akı rozkošnı duch psa.
Mal by som ho radšej necha tak.
Opitı ako èík!
Napísané: `NÁRADIE A BRIGA`
`NEVSTUPOVA`
Huch!
Odporné! Pozrite sa, ako erú!!!
Vyzerajú ako kurèatá.
Vyzerajú ako kurèatá.
Vyzerajú ako kurèatá.
To je pierko.
Pierko z ducha kurèaa.
Nemôem nájs miesto, kde je šteklivı.
Len si vezmem tento starı koreò a padám.
Je to prázdna protikoreòová voodo truhlica.
Nevidím na tom niè zvláštne.
Okrem ve¾kého iariaceho voodoo protikoreòa vnútri.
Nemôem sa dosta dovnútra.
Je to pribité, zareazované, zvarené, zaviazané, prilepené a zletované k sebe.
U je to otvorené.
Nemôem sa dosta dovnútra.
Je to pribité, zareazované, zvarené, zaviazané, prilepené a zletované k sebe.
U je to otvorené.
Nemôem sa dosta dovnútra.
Je to pribité, zareazované, zvarené, zaviazané, prilepené a zletované k sebe.
U je to otvorené.
S tımto by to malo ís...
Je to skrútené a vysušené a nie ve¾mi pekne vyzerajúce.
Je to plné nejakej uhlíkovej tekutiny.
Nemyslím si, e je to v tejto forme nejako pouite¾né.
Teraz nie.
Má to k¾úèovú dierku.
Je to pevne zamknuté, musí tam by nieèo dôleité.
Je to zamknuté.
Jediné, èo som z toho dostal, je toto pierko.
Nemôem sa tam dosta.  Ten ve¾kı duch mi leí v ceste.
Hej!  Stavím sa, e guvernérka je vnútri!
Nemôem sa tam dosta.  Ten ve¾kı duch mi leí v ceste.
Je to ve¾ké.  Je to zamknuté.
Nechcem ho prebudi, kım nebudem ma nejaké protiduchovské sérum, aby som sa mohol bráni.
Zaspal.
Je to rozeravené náradie duchov.
Oh dobre, viac predmetov.
z
zz
zzz
zzzz
zzzzz
zzzzzz
zzzzzzz
zzzzzzz
zzzzzzzz
Je to sud masti na smaenie.
U je to otvorené.
Fuj, mám to celé na rukách.
U mám dos.
Skúšam nasıtené tuky obmedzi.
Myslím, e tieto potkany majú dos.
To nie je dobrı nápad.
Je to prázdna miska.
Tak toto zobra nehodlám...
...je to pokryté slinami od potkanov.
Myslím, e tieto potkany majú dos.
To nie je dobrı nápad.
Vyzerá opitı.
Vyzerá opitı.
K tej potkanej príšere sa nepriblíim.
To je najväèší duch potkana, akého som kedy videl.
Nalejem to do tejto misky.
Nemyslím si, e to chce.
Fuj, mám to celé na rukách.
U som na to dal dos masti.
U by to nemalo škrıpa.
Toto ma len tak prekåznu nenechá.
Toto ma iba zasviní.
Jaj!  Nenávidím potkany!
No, pozrite sa na to.
Je to návod, ako získa ïalšiu hlavu!
Mohli by sme mu da našu starú hlavu a poui tento návod na získanie novej!
Áno, tu ju máš.
Vïaka.
Pekná hlavièka, však?
Dríme ju omotanú magickım náramkom. Stáva sa tak nevidite¾nou.
Oh, pozri.
Myslím, e sa jej páèiš.
Musíš sledova jej nos, zavedie a do LeChuckovho úkrytu v katakombách.
Potom získaj koreò, vrá sa spä...
...a my ti namiešame špeciálny rozpúšací enzymatickı roztok.
Potom to môeš vylia na LeChucka ako so¾ na slimáka!
Super!
Ve¾a šastia.
Poèka!
Èo?
Kde sú vôbec katakomby!
Oh áno, je to vlastne tá ve¾ká Opièia hlava na vıchodnej strane ostrova.
Nemôeš to minú.
Ve¾a šastia!
Hej, vïaka!
U som si myslel, e to nikdy neuvidím!
No, teraz im môeš ís vráti k¾úè od Opièej hlavy.
OK.
A neboj sa, nepouijem ho.
Nie, vïaka, mám u jeden.
Hoci by som si elal nájs ešte jeden.
Èo s tım akoe budem robi?
Hej, HAŠLERKY!
To je to, èo mi najviac chıbalo na civilizácii.
Peniaze, tie ti budú naniè.
U som preèítal to¾ko správ, aby mi to vydralo do konca ivota.
Nie, vïaka, mám svoje vlastné, hoci ich niekto hodil do priepasti.
Èo s tım akoe budem robi?
Èo je to?
Oh, nie.
To nie je dobré.  Vôbec nie.
Zháòam loï a posádku, aby som ju zachránil.
Hmmm...
Mám pocit, e to budem ¾utova, ale rátaj so mnou.
Uvidíme sa v prístave.
Nechcem to.
Hej...
Huch!
Nemôeš ma takto ¾aka!
Prepáè.
Ešte ijem.
Ahhhhhhhhhhhhhhhhhhh
To je tá strašidelne vyzerajúca loï duchov, ktorú som videl odpláva s guvernérkou!
Je pekne strašidelnı.
ÍÍP!
Vystrašil si ma na smr!
Peknı hojivı vánok tu máme, však?
U si ochutnal koreòové pivo, ty diabolskı prízrak!
Èo sa stalo s loïou?
Mohol by si, prosím a, presta robi to s tou hlavou?
Tam dole je to stále rovnaké.
Poèkaj!
Ak h¾adáš Lechuckovu posádku, môem ti poveda, kde sú!
Tú loï nikdy nenájdeš...
Iste.
Povedz mi, kam odišla loï.
Myslím, e a aj tak tresnem.
Prosím! Mám enu a tri deti!
Chceš vedie, kde je LeChuck a jeho celá posádka?
Èo som ti kedy urobil?
Ale ja som PRIATE¼SKİ duch!
Úprimne.
Ak ti to poviem, s¾ubuješ, e mi neublíiš?
OK, s¾ubujem.
iadne s¾uby, duch.
Nemôem s¾úbi, e ti nijako neublíim.
OK.
iadne rozprávky, èloveèe.
Èo?
Všetci odišli na svadbu.
Akú svadbu?
Kde je tá svatba?
Musím ís za nimi!
Vzdávam to.  Som unavenı z toho veèného prenásledovania.
Preèo tu EŠTE si?
LeChuck si berie guvernérku na ostrove Mêlée™.
ÈO?
Ale ako budú to...
Na ostrove Mêlée™ je peknı kostol.
Mali namierené tam.
LeChuck si berie guvernérku!
Berie si ju—
Ostrov Mêlée™?
Oh, to nie!
Spadla mi hlava do lávy a ja som pre òu musel skoèi...
...a keï som sa vynoril, tak u boli všetci preè!
Ve¾ká škoda.  Nenávidím premeškané svadby.
Musím tú svadbu zastavi!!
Èo?
Teraz to nemôeš vzda!
Èo si to vôbec za hrdinu?
Máš pravdu!
Maj sa!
Vau!
Hej, pohni si, musíme u ís!
LeChuck chce zase zmiznú s guvernérkou!
Bob!
Èo tu robíš?
Oh, zmeškal som loï na svadbu.
Hej!
iadny problém!
Vezmeme si moju!
Ideme!
...hej...
Najskôr budeme musie splaši loï.
Ako ste sa sem dostali bez navigátora?
Èo sa stalo s tvojou loïou?
Je v obchode.
Nie som poistenı, aby som to riadil.
Ukradla ju moja posádka a odplávala sa s òou opa¾ova na Ipanemu.
Pred chví¾ou som ju tak trocha potopil kameòom.
{verb:global_100}
Oh.
To je dobré.
Môeme si vzia moju.
Ty máš loï?
Ak máš loï, tak preèo èakáš na záchranu?
Vezmeš ma na ostrov Mêlée™?
Ako ste sa sem dostali bez navigátora?
Uf.
Preèo asi. Keï stroskotáš, MUSÍŠ by zachránenı.
Ako to stojí v pravidlách.
Poièiam ti loï, keï mi s¾úbiš, e ma s òou zachrániš.
OK.
Mám hlavu.
Ideme.
Oh, tu si!
H¾adali sme a všade.
Musíme sa dosta naspä na ostrov Mêlée™!
Ako si sa sem dostal bez hlavy?
Vy poznáte tento prieh¾adnı prízrak bez tieòa?
iadne arty.
No hej, u nám došiel opa¾ovací krém.
Èo?
Er...
No, myslel som tım, to je jedno —
ÈO?
Heh, uh...
Nevadí.
Myslíš toho s tou šmyk¾avkou na hlave?
Musíš sa zbavi tejto posadnutosti s hlavami, Threepwood.
Iste, je to starı pirátsky kamoš.
Hovorím, e ho vezmeme.
Vïaka, Otis.
Tak rıchlo, ideme.
Uvidíme sa, Bob.
...hej...
Bob!
Ahoj, Bob!
Èau, chlapi!
Povedz, Bob, vyzeráš trochu bledı...
No, ja som bledı normálne.
Koniec-koncov, u som màtvy.
Màtvy?
Ako sa to stalo?
Oh, normálne,
vyplávali sme rabova,
objavila sa loï duchov,
LeChuck zabil celú posádku,
a potom nás prevelil na svoju loï.
Veï vieš.
Kriste, tak to je hrozné.
Nechcel by si sa pripoji k našej ceste za dokonalım opálením?
No, to by bolo pekné, ale pokúšam sa chyti loï na svadbu guvernérky na ostrove Mêlée™.
(tm).
V tom prípade máme rovnakú cestu.
Môeš ís s nami.
Super!
Myslel som si, e v pekle huby porastú.
Temnı a nejasnı.
Temnı a nejasnı.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Temnı a nejasnı.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Radšej sa toho nebudem dotıka.
Fuj.  Neznášam huby.
Radšej sa toho nebudem dotıka.
Fuj.  Neznášam huby.
Odporné.
Fuj.
Hrozné.
Pekelné.
Hnusné.
Nechutné.
Aké hnusné.
Ak sa na tie odporné veci budem musie pozera ešte o trochu dlhšie, tak budem vraca.
Fuj.
Èudné.
Hnus.
Pripomína mi to nieèo, èo som mal v noènej more.
Vyzerá to tak odporne, ako to smrdí.
Ohavné.
Toto je strašné.
Príšerné.
Hnusné.
Bezdôvodné a morbídne.
Toto mi naháòa husiu kou.
Extrémne nepríjemné.
Poburujúce, a ešte k tomu sa mi to páèi.
No, toto nie je zase také zlé.
Hmmm...  Vieš, niektoré z tıch vecí sa mi zaèínajú páèi.
Pekné!
Skvelé!
Drsné!
Ak odtia¾to skoro nevypadnem, tak sa z toho zbláznim.
Mohol by som sa na to pozera veène.
I keï u sa na to pozerám viac ako dvadsa rokov.
A tie preto, e toto je jediná vyhliadka na tomto ostrove.
Toto je môj starı priate¾, s ktorım som sem priplával.
Pozerám, e schudol.
Nikdy nevyzeral lepšie.
Opièia hlava je kus práce, èo si myslíš?
Škaredı príklad ltého mazu.
Oh, ahoj!
Iba tu h¾adám nespo¾ahlivıch domorodcov, aby mi vrátili môj zberaè banánov...
...ale nemôem ich nájs.
Pozri sa tamto na tú skvelú loï!
Prišiel si s òou?
Prišiel si v tej lodi, èo som tamto videl?
Si statoènejší, ne vyzeráš.
Hoci vyzerá ako loï, ktorá mi kedysi patrila...
Áno, je to krásny vıh¾ad.
O seba sa ve¾mi nestarám.
Èo sa mu stalo?
Vyzerá dos zle...
Videl som odtia¾to odchádza opicu.  Urèite to urobila ona.
Er, prepáète.
Chcel som zaklopa, ale nevidím tu iadne dvere.
Klopal som, ale asi ste to nepoèuli.
Áno, je to celkom zaujímavé.
Èo?
Dostal som ju od mua menom Stan...
Èo tım myslíte, `statoènejší ne vyzerám`?
Nechaj ma tak, ok?
Um...
Obávam sa, e budem musie ís.
Neodkladné záleitosti, vieš.
— hi hi —
Nebuï naivnı.
Oh, šialená nehoda.
Skúšal pripevni hojdaèku.
Mohla to by skvelá turistická atrakcia, keby ostrov vôbec niekto našiel.
No, to je OK.
Nabudúce buï viac opatrnı.
Stan, Stanovo vrakovisko?
Na ostrove Mêlée™?
Hih hih hih hih
Hej, neukaj.
Mám len jeden jedinı.
Nikdy som ho nevidel, aj keï bol ešte naive!
Nerob zo mòa blbca, synak.
Oh, niè.
Nevadí.
Si nieèo ako stroskotanec?
Ako to myslíš, e vyzerám ako zamestnanec?
Vypoèuj si toto:
Som nieèo ako stroskotanec?
Hih.
Myslel som si, e ostrov je neobıvanı.
Kto si?
S kım si myslíš, e hovoríš?
Bude lepšie, keï pôjdem.
No, myslel si si zle.
Ja?
Preèo asi, ¾udia sledujú, samozrejme.
Um... iste.
Volám sa Toothrot.  Herman Toothrot.
ijem tu.
No, nie presne tu.
V pevnosti na sopke.
Stroskotal si?
Myslíš si, e som tu na rehabilitácii?
Ach, chlapèe.
Ako si sa sem dostal?
Take nie si jedinı na tomto ostrove?
iješ tu sám?
Poièal si nieèo kanibalom?
Som Guybrush.  Prišiel som niekoho zachráni.
Povedal si, e si dostal k¾úè od miestnych domorodcov?
Mám váš zberaè banánov.
Preèo mi jednoducho nedáš ten k¾úè?
Èo sa ti stalo so spodkami?
Prepáè, musím ešte nieèo zariadi.
Áno, ja tie.
— hi hi hi —
No, priplávali sme sem s mojim priate¾om pred dvadsiatimi rokmi.
Dúfali sme, e odhalíme tajomstvo Ostrova opíc™.
Ale môjho priate¾a postretla desivá tragická nehoda,...
...ktorá si vyiadala jeho ivot...
...a sám som nemohol odpláva naspä.
Vytrénoval som tlupu šimpanzov ako posádku lode, a poslal som ich spä na ostrov Mêlée™.
Mali nájs pomoc a vráti sa pre mòa...
...nieèo sa muselo sta.
Preèo si neplával so šimpanzmi?
TİDNE na lodi plnej opíc???
Oh, dobrı vtip.
Som jediná CIVILIZOVANÁ osoba na ostrove.
Sú tu miestne kmene zberate¾ov trofejí—
—no, skôr zberate¾ov hláv—
—ale nerozprávam sa s nimi.
Sú to kanibali, ale nie sú nebezpeèní...
...teda pokia¾ im nieèo nepoièiaš.
No, tak som tu.
Šastnı, e si ma prišiel zachráni—
—hoci si mohol dorazi trochu skôr.
Pokuta za knihu, ktorú som nevrátil spä do kninice, bude teraz pekne mastná.
Poïme.
Er...
Tak som to presne nemyslel.
Priplával som sem zachráni guvernérku Marleyovú z ostrova Mêlée™, ktorú uniesol duch.
Oh, fajn, NEZACHRAÒUJ ma.
Mám to tu rád.
Prší mi na hlavu, fúka mi na chrbát...
...a na tanieri mám chrobáky...
Um...
No, samozrejme by som a mohol zobra so sebou...
...ale najskôr musím nájs guvernérku.
Oh, to nie je problém.
Mám dojem, e je na lodi duchov, v tajnom podzemnom úkryte.
Fakt?
Ako to vieš?
Ako sa tam dostanem?
Najjednoduchšia cesta je skrz ve¾kú Opièiu hlavu.
Bol som vnútri, pred pár rokmi.
Budeš potrebova k¾úè.
Dostal som jeden od miestnych domorodcov.
...ale najskôr musím zachráni guvernérku.
Myslím, e je na lodi duchov.
Oh, OK.
Poièal som im zberaè banánov, a nikdy mi ho nevrátili.
Ako zástavu mi dali tento ohromnı bavlnenı mop.
To otvorí Opièiu hlavu, u chápeš?
To otvorí ve¾kú Opièiu hlavu, ktorú uctievajú.
Nie e by som niekedy potreboval ís do Opièej hlavy...
...ale ak to chcú spä, musia mi vráti môj zberaè.
Je to otázka hrdosti, vieš?
U som ti povedal o mojom zberaèi banánov a e ho nemám ešte spä, však?
Aké spodky?
Nie, potrebujem vráti zberaè banánov.
—urk—
aké dıchanie!
—dusenie—
Ajjjéééé!
To nie je kostol.
Tadia¾to sa nejde do kostola.
To nie je kostol.
Tadia¾to sa nejde do kostola.
To nie je kostol.
Ps
Pss
Psss
Pssss
Psssst.
Hej TY.
Poï sem.
Vaša rezervácia je na 2:30, pane.
Potom sa zastavte.
Máte rezerváciu?
Môem vám pomôc?
Prišiel som vykradnú sídlo guvernérky.
Práve som na ceste do sídla guvernérky.
Musím by na nesprávnom mieste, uvidíme sa neskôr.
Prišiel si to tu vylúpi?
Áno.  Lúpenie je zábavné, teraz u som pravım pirátom.
Rozhodne nie!
To je dobré...
...pretoe u sme zarezervovaní na ïalsích 5 hodín.
A máte rezerváciu, pane?
Rezerváciu?!?  Na vylúpenie?
Áno, mám rezerváciu.
Kriste, nemám rezerváciu.  Mal som najskôr zavola?
Oh áno, ve¾mi populárne, keï je guvernérka preè.
Chaos by mohol narasta bez nejakého systému.
No...
...pokia¾ nemáte rezerváciu, budete musie odís.
A na aké meno by to malo by?
Threepwood, Guybrush Threepwood.
Ah... Myslím, e to je hneï to prvé na zaèiatku zoznamu.
Je to pod 'K', ako Koleno.
Prepáète...
...vaše meno tu nevidím.
Samozrejme...
Peknı pokus...
...ale...
Peknı pokus...
...ale...
Samozrejme, e ste mali najskôr zavola.
Toto miesto je ve¾mi ob¾úbené.
Teraz...
...u máme obsadené na ïalších 5 hodín.
Ale mohol by som vás tam nejako vsunú...
...okolo druhej hodiny.
Bude vám to vyhovova?
Áno, to by mohlo by fajn.
Nie, vïaka, nestihol by som loï.
Super...
Píšem si vás - `Jedno vylúpenie sídla guvernérky na 2:30`, buïte presnı.
Nabudúce zavolajte vopred.
Ako si eláte.
Takto by som mohol skonèi, keï rıchlo nevypadnem.
Keï na to príde, takto u som takmer skonèil.
Nie, vïaka.  Stále je na tom kus mäsa.
Nie, vïaka.  Stále je na tom kus mäsa.
Nie, vïaka.  Stále je na tom kus mäsa.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Èo?
Vidím pod chatrè!
Vyzerá ako uvo¾nená.
U je to otvorené.
U je to otvorené.
U je to otvorené.
Teraz u môem poui dvere.
Pekná malá lebka.
Niè sa nestalo.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
Obesi sa nie je to pravé riešenie.
U je to zatvorené.
Cez to sa nedostanem.
Neotvára sa to.
Je tu napísané, `V prípade nálezu, prosím, vráte Hermanovi Toothrotovi.`
Viac banánov nebudem potrebova.
Viac banánov nebudem potrebova.
U som ho zobral.
Nie sú tu iadne banány.
Ja preleziem, ale zberaè banánov je ve¾mi ve¾kı.
Je to zamknuté.
Myslím, e je to zvarené.
Je to zamknuté.
Myslím, e je to zvarené.
Nebudem si to oblieka skôr, ne získam sošku.
Nemyslím si, e sa to tım dá otvori.
Je to zamknuté.
Myslím, e je to zvarené.
Je to zamknuté.
Myslím, e je to zvarené.
Teraz to nepotrebujem.
Vyzerá rozrušene.
Rozpráva so smrtiacim dychom?  Nie, vïaka.
Je to aké.
Je to hrubı eleznı pilník.
Vnútri je pilník!
Take ty si ma prišiel zachráni?
Prišiel si zase vypoèúva väzòa, hm?
Kto si?
Èo si spravil, e si skonèil tu?
No, a aká je tu strava?
Èo si to hovoril o kvetoch?
Kto a obvinil?
Šerif je iste idiot, však?
Kto je tu šerif?
Guvernérka bola unesená!
Ak a dostanem von, pripojíš sa k mojej posádke?
Nemáš u seba náhodou pilník?
Môem ti nieèo prinies?
Nu, tak maj uši nastraené.  Musím ís.
Volám sa Otis.
Aspoò si to myslím.
U som tu dos dlho na to, aby som si to pamätal.
Musíš ma odtia¾to dosta skôr, ne sa z toho úplne zbláznim!
Nevidíš, e som nevinnı?
Ale preèo si vo väzení, keï si nevinnı?
Nepripadáš mi takı nevinnı.
Obvinili ma!
Ale ja som sa tıch blbıch kvetov ani nedotkol!
Akıch kvetov?
Mohol by si mi poveda názov tıch kvetov ešte raz?
Kto a obvinil?
Aká je tu strava?
Èo si hovoril, e tu ješ?
V lese nájdeš lté kvety Caniche Endormi—
Ale ich zbieranie je protizákonné.
Neviem, kto presne...
Myslím, e to bolo sprisahanie.
A ak je nieèo, èo naozaj neznášam...
...tak je to sprisahanie.
Tie by si to robil, keby si tu bol tak dlho ako ja.
Niè som neurobil.
A u vôbec nie tım blbım kvetom.
To kvôli nim som tu, kvôli blbım kvetom...
Neartujem.
Ty si ešte nenarazil na šerifa?
Tak to máš šastie.
Šerifovi Festerovi je lepšie sa vyhıba.
Fester kto?
Èo je na òom také zlé?
Hovoríš to iba preto, lebo a zavrel do väzenia.
Budem na to pamäta.  Uvidíme sa neskôr.
Fester je ten najotravnejší chlap na ostrove Mêlée™.
Našastie ho guvernérka udriava väèšinu èasu na uzde.
Kedysi sme mali férového skromného šerifa—
—ale ten náhle zomrel za záhadnıch okolností.
Pod¾a môjho názoru, s tım má novı šerif nieèo do èinenia.
Myslím, e u si povedal dos, Otis!
Hups.
Nie!  Spıtaj sa kohoko¾vek...
Zoeò mi právnika!
A lacného!
Iste!
Samozrejme!
Pri mojej nezamestnanosti budem doivotne zadåenı.
Tak zatia¾.
Èo?
Tu, pozri sa na toto.
Uniesli guvernérku?
Tak to ma ozaj naštvalo.
Potreboval by som niekoho nakopa.
Hmmm...
Zaujímalo by ma, èi náhodou nenechala otvorenı byt...
Áno...
DOSTAÒ MA ODTIA¼TO!
Vlastne, èoko¾vek, èo by ma zbavilo tıch potkanov, by bolo fajn.
Vımenou by som ti mohol da tento mrkvovı koláè od tety Tillie.
Neznášam mrkvové koláèe.
Myslíš, e by som tu inak bol?
Všetko èo mám, je mrkvovı koláè, èo mi urobila teta Tillie.
Dám ti ho, pokia¾ mi prinesieš nieèo proti tım hnusnım potkanom.
Nemôem vystá ten mrkvovı koláè.
Pekne ïakujem.
Oh, veï vieš, ako zvyèajne...
Breèku, grog, kašu...
Potkany, èervy, a vši, keï si nejaké nachytám.
Mám tu mrkvovı koláè, ktorı mi upiekla teta Tillie, aj keï vie, e sa mi mrkvové koláèe úplne hnusia.
Vlastne, kuchár v Scumm Bare je môj starı priate¾, a obèas mi prepašuje nejaké jedlo.
Ako napríklad bravèové zvyšky, väèšinou kopıtka a pery - ale obèas...
...mi prinesie aj kúsok spálenej peèienky...
To je odporné.  U nechcem viac poèu.
Èo je zlé na spálenej peèienke?
Hej, to ty si sa pıtal.
No, iadnu inú peèienku s chvostom som nikdy nevidel.
Pozri, mám rád návštevy a tak podobne,
ale u ti nemám ve¾mi èo poveda.
Navyše mi od toho rozprávania vyschlo v krku.
Preèo si nenájdeš na rozprávanie niekoho iného?
Nie som poslednı pirát na tomto ostrove.
Povedal som, e ti u nemám èo poveda.
Pozri, som ti vïaènı, e sa mi snaíš robi spoloènos a tak podobne...
Ale pokia¾ nie si právnik...
...alebo nevieš o nejakom spôsobe, ako ma zbavi zámku od cely...
...skutoène nevidím dôvod, preèo by sme mali pokraèova v rozhovore.
Musíš ma odtia¾ dosta!
Som obeou spoloènosti.
A tie aj obeou páchnuceho dychu.
Fuj!
Hej, je ve¾mi aké udriava mentolovo sviei dych, keï tu nie je niè pod zub, okrem tıch potkanov.
Ale ja to potrebujem, aby som sa dostal k soške.
Ooooh!
Grogmentolové!
Aké osvieujúce!
Vïaka.
Hej, to by mohlo fungova na potkany!
Vïaka!
Tu máš koláè.
Vımenou si vezmi tento mrkvovı koláè.
Upiekla ho teta Tillie.
Veï som ti povedal, e NENÁVIDÍM mrkvovı koláè!
Nepotrebujem tvoju dobroèinnos.
No, mono len jeden kúsok.
Nechcem niè viac, ne slobodu!
...a mono hašlerky.
...a mono nieèo na zbavenie sa tıch potkanov.
Èloveèe!  Hovor mi o zlom dychu!
Mimochodom, volám sa Otis.
Ak je nieèo, èo pre teba môem urobi—
No, vlastne, je tam nieèo...
H¾adám statoènıch ¾udí do mojej posádky, aby so mnou vyplávali na Ostrov opíc™ zachráni guvernérku.
Bola unesená desivım pirátom LeChuckom, a drí ju proti jej vôli na nejakom tajnom mieste.
Chápem...
No, áno, hmmm...
LeChuck, hovoríš?
Musíme vypláva na Ostrov opíc™ a—
HEJ!  POZRI SA!  ZA TEBOU!  TROJHLAVÁ OPICA!
Nechápem, ako som mu na to mohol skoèi.
Ale ako trik to bolo dobré.
Dúfam, e si nebral toho špinavého pova¾aèa príliš váne.
Urobil by všetko preto, aby si nemusel odsedie trest.
Pripadá mi nevinnı.  Preèo ho neprepustíte?
Je ŠPINAVİ.  A stršne smrdí.
Prepáète?  Práve máme súkromnı rozhovor.
O môj boe!  POZRI sa na èas!  Chcel by som zosta a porozpráva sa, ale...
Mono by si sa mal stara o seba, cudzinec.
O tom, kto je vinnı alebo nevinnı, tu rozhodujem ja.
Hey, vïaka.
Asi máš naozaj silné nervy, keï si prídeš do mesta a vynášaš súdy nad miestnymi.
Ak sa ti nieèo nepáèi na tom, ako smrdíme, môeš sa kedyko¾vek zobra a odís.
Neopová sa hovori so mnou takım tónom, opièiak.
Alebo a s radosou strèím do cely k Otisovi...
...potom budete ma na súkromnı rozhovor kopu èasu.
Chápem.
Máš èas sa priateli s kriminálnikmi, ale nemáš èas na tıch, ktorí tu udriavajú zákon.
Prepáète.
Pozri, neviem èo máš za lubom...
...ale èoko¾vek to je, tak je to urèite nelegálne.
Tak si dávaj bacha.
Kdeko¾vek pôjdeš na Mêlée, budem a sledova.
A ak sa pokúsiš o nejaké darebáctvo, skonèíš tu raz a navdy.
Èloveèe, to je magor!
Vidíš, èím musím prechádza?
Mal by si radšej ís, ne nás oboch dostaneš do problémov.
It's some sort of meat or meatlike substance...
Niekto v tom uvaril tlaèenku.
Je to sleï.
Tá hydina mi takmer odzobala moju ruku...
Je to plné toho hnusu, èo pijú piráti.
Myslím, e u mám dos.
Nechcem toho to¾ko.
Hmm.  Mäso s omáèkou.
Hmm.  Ryba s omáèkou.
Varí sa to.
Varí sa to.
Tá doska je zaseknutá.
Nie je to práve bobkovı list, ale kadı kuchár pouíva náhrady.
Nemyslím si, e to potrebuje MÄSO a RYBU.
Nechcem to tam da.
Au!
To páli!
Vau!
Ten to do seba hodil!
Mono a zjeme, mono a necháme ís.
Musíme si o tom pohovori s našim dietológom.
Poï.  Ukáem ti chatrè pre hostí.
Odtia¾ nám neuteèie.
Práve teraz sa na mapu pozera nepotrebujem.
Myslím, e nájdem cestu do prístavu aj bez nej.
Nechcem to tu poloi...
...niekto to môe ukradnú.
Práve teraz sa na mapu pozera nepotrebujem.
Nechcem to namoèi.
Práve teraz sa na mapu pozera nepotrebujem.
U to mám!
Toto nie je mapa!
Vyzerá to ako...
...lekcie tanca!
Mám jednu zlatku.
Mám dve zlatky.
Mám 172 zlatiek.
Mám 172 zlatiek.
Mám 202 zlatiek.
Mám 203 zlatiek.
Mám 247 zlatiek.
Mám 248 zlatiek.
Mám 272 zlatiek.
Mám 273 zlatiek.
Mám 277 zlatiek.
Mám 278 zlatiek.
Mám 302 zlatiek.
Mám 303 zlatiek.
Mám 348 zlatiek.
Mám 371 zlatiek.
Mám 373 zlatiek.
Mám 377 zlatiek.
Mám 378 zlatiek.
Mám 402 zlatiek.
Mám 403 zlatiek.
Mám 447 zlatiek.
Mám 448 zlatiek.
Mám 478 zlatiek.
Mám 174 zlatiek.
Mám 175 zlatiek.
Mám 204 zlatiek.
Mám 205 zlatiek.
Mám 249 zlatiek.
Mám 250 zlatiek.
Mám 274 zlatiek.
Mám 275 zlatiek.
Mám 279 zlatiek.
Mám 280 zlatiek.
Mám 304 zlatiek.
Mám 305 zlatiek.
Mám 350 zlatiek.
Mám 373 zlatiek.
Mám 375 zlatiek.
Mám 379 zlatiek.
Mám 380 zlatiek.
Mám 404 zlatiek.
Mám 405 zlatiek.
Mám 449 zlatiek.
Mám 450 zlatiek.
Mám 480 zlatiek.
Mám dos peòazí na všetko èo potrebujem.
Mám dos peòazí na všetko èo potrebujem, okrem lode.
Nie som si istı, ale myslím, e zaspal.
Nejaká známka po guvernérke?
Niè.
Ako som u povedal, mám strach, e sme ju videli naposledy.
Pozri, povedal som ti—
e som niè nevidel.
Ak máš o òu strach, choï a nájdi si ju sám.
Pozri, mám tu teraz dos práce.
Porozprávame sa neskôr.
Poèul som, e tu niekde bude grilovacia párty.
H¾adám nejakú zábavu.  Nevieš o nieèom?
Èo je zelené a chlpaté a má tisíc nôh?
Predstavoval si si niekedy, e by sme mohli by postavy z románu?
Pozri!  Ha ha.  Chápeš?
Huch!
Oh, to si zase ty, Throozwald.
Oh, to si zase ty, Thumpwood.
Oh, to si zase ty, Thratwook.
Oh, to si zase ty, Thrutwalk.
Oh, to si zase ty, Threebwalk.
Oh, to si zase ty, Threetwink.
Takmer si ma vystrašil na smr.
Myslel som si, e si—
—to je jedno.
Ako si povedal, e sa voláš?
Som Guybrush Threepwood.
Vlastne, moje meno je Guybrush Threepwood.
Èo je tak èudné na mene `Guybrush Threepwood`?
Hovor mi Squinky.
Som za vami.
KTO SI?
Preèo má guvernérka strach z nepozvanıch návštevníkov?
Práve odchádzam h¾ada svoje šastie.
Prišiel som na ostrov Mêlée™, aby som sa stal pirátom.
No, lepšie si si u vybra nemohol.
Ale prichádzaš v zlı èas.
A to nespomínam tvoje meno.
Máš to najhlúpejšie meno, aké som kedy poèul.
To je jediné meno, ktoré je trápnejšie ne meno `Squinky`.
OK, Squinky.
Práve si povedal, e sa voláš Gibberish Driftwood, alebo tak nejak.
GUYBRUSH THREEPwood.
Iste, iste.
Eh?
Oh.
Som pozorovate¾ ostrova Mêlée™.
Sledujem oceán kvôli prichádzajúcim búrkam a lodiam, a hneï to hlásim guvernérke.
Nemá rada nepozvanıch návštevníkov...
...hlavne nie teraz.
Povedz, kto si?
Je to THREEPWOOD.
Èo je tak èudné na mene `Guybrush Threepwood`?
Preèo má guvernérka strach z nepozvanıch návštevníkov?
Ako si sa mohol sta pozorovate¾om, keï si evidentne slepı ako netopier?
Tu som.
Hneï vyrazím h¾ada svoje šastie.
Vlastne to sú OÈAKÁVANÍ návštevníci, o ktorıch hovoríme a ktorıch sa bojíme.
Obzvláš jeden pirátsky kapitán...
Síce u màtvy, ale to z neho nerobí menej nebezpeèného.
Pozor na jazyk.
Vybral ma priamo náš šerif!
Eh?
Oh.
Oh, dobre.
Nie je to náhodou to isté?
Niè, pokia¾ chceš by predáva topánky.
Ak chceš by pirátom, chlapèe, dám ti radu:
Zmeò si meno.
Skús nieèo ako `Strachofúz` alebo `Šesprstı Pete`.
Ve¾a šastia.
Zdravím vás!
Volám sa Guybrush Threepwood a chcem sa sta pirátom!
Huch!
Takto ma vystraši!
Ehm...
Len vás zdravím.
Ah!
No, dobre, Thriftweed—
THREEPWOOD.
Guybrush THREEPWOOD.
No jasné.
Take ty sa chceš sta pirátom, èo?
Vyzeráš skôr ako somrák.
Ale ak to myslíš váne, choï sa porozpráva s vodcami pirátov.
Nájdeš ich v Scumm Bare.
Fajn, vïaka!
Idem tam!
Zatia¾ sa majte.
Odchádzam h¾ada svoje šastie!
Ve¾a šastia.
Um...
Kde si hovoril, e ich nájdem?
V SCUMM BARE.
Dobre.
Vïaka.
Guvernérka Elaine Marleyová.
Take ja som ti ju dala, èo?
Take som ti ju poièala, èo?
Take moja soška patrí do múzea, hm?
Take a k tomu prinútili vodcovia pirátov, hm?
Take ideš s mojou soškou na prechádzku, èo?
Uh...
Nu...
No...
Uf...
Upokojte sa, pán Threepwood.
Viem, preèo tu ste.
Verte mi, e nie ste prvı, kto sa o to pokúsil.
Hoci musím prizna, e sa nikto nedostal tak ïaleko ako vy.
Er...
Um...
Viete...
Vlastne...
Pozorovate¾ mi povedal o vašom príchode.
Chcela som sa s vami zoznámi, akonáhle som zaèula vaše fascinujúce meno.
Povedzte mi, Guybrush, preèo sa chcete sta pirátom?
Nevyzeráte ako jeden z nich.
Vaša tvár je príliš...
...sladká.
Blfft...
Grlpyt...
Hrdrl...
Rldft...
Chápem...
No, zrejme nemáte náladu na zbytoèné kecanie, všake?
Domnievam sa, e máte ve¾a inıch vzrušujúcich vecí na práci.
U vás viac nebudem zdriava, pán Threepwood.
Bgglw!
Mfrnkf?
Dmnkly...
—hehmm—
elal by som si, aby som vedel rozpráva so enami.
Na èo tak èumíš?
`Stará dielòa na gumené-kurèatá-s-kladkou-uprostred...`
`...Slúime Vašim gumokladkovskım potrebám u vyše 50 rokov.`
Musím sa dosta do kostola!
Kostol je opaènım smerom!
Na èo tak èumíš?
Tu je celkom dos pravopisnıch chıb.
To sú PRAVOPISNÉ chyby, nie gramatické.
Braaaak!
Desa hodín.
Hmm.  Stále desa hodín.
Vyzerá to, e na ostrove je STÁLE desa hodín.
Desivé!
Prepáète.
Máte nejakú pozvánku na svadobnı obrad?
Áno mám, preèo.
Nie, som nevítanı hos.
Nie, ale mám toto kúzelné smrtiace koreòové pivo.
Musel som ju necha v druhıch nohaviciach.
Môem ju vidie, prosím?
Nie.
Iste, je v tejto f¾aške od sódovky.
Er, myslím, e som ju nechal v druhıch nohaviciach.
Zatia¾ dovidenia.
Nie tak rıchlo, kamoš!
Nepripadáš mi príliš ako duch.
Si príliš ruovı...
Ve¾a som sa opa¾oval.
Trpím vzácnym syndrómom prehnanej pigmentácie.
Neber to koreòové pivo príliš osobne.
Vôbec mi neznieš ako duch.
Mohol by si zakvíli, zastona, zarinèa reazami alebo také nieèo?
aaAAÚÚÚÚÚúúúúú...
Dal som reaze odmasti do èistiarne.
Neber to koreòové pivo príliš osobne.
Povedal by som, e znieš skôr ako môj pes.
Dobre, OK.
Ale kde je ten zatuchnutı, plesnivı, záhrobnı, duchovskı pach?
Asi to presmradil tvoj vlastnı záhrobnı smrad.
Aha!  Tak ma nechaj da si dole topánky...
Je to nová koreòová pivná kolínska.  Nechceš ju vyskúša?
Sleduj...
Nie, to je v pohode.
Ak si naozaj duch, tak to doká.
Uká mi, ako si dávaš dole hlavu.
Er...
Um...
Dobre...
Myslíš hlavu na tomto pive?
Oh, zabudni na to!
Toto je super vec!
Teš sa, LeChuck!
V meste je novı šerif a volá sa—
-Hej!  Radšej by som sa mal dosta do kostola!
Hej!!  Nešliapni na potkana!
Povedal som, neotravuj toho potkana!
Nebudem a varova ešte raz!!
Nechaj toho potkana na pokoji!!
Hej, èloveèe!!
Frank, nech s tım prestane!
Ou, pozri sa, èo si urobil!
Ospravedlòujem sa za to, èo som povedal o potkanoch.
Ospravedlòujem sa za toho potkana...
Teraz keï je tá strašná príšera preè, môeme sa rozpráva.
Hej, peknı potkan!
Ako môeš stá tak blízko u tejto hávede?
Chlapi, poznáte toho podozrivo vyzerajúceho chlapíka na opaènom rohu?
Neviete, kde by sa tu dala splaši mapa k pokladu?
Vezmem si tie zápisky, len keï mi zaplatíš dve zlatky.
Ešte by som sa chcel spıta.
Povedzte, ste piráti?
Viete o tom, e guvernérku uniesli?
U musím ís.
Videli sme a, ako kupuješ mapu od toho chlapíka naproti.
U si sa na òu pozrel?
Ha ha ha ha ha ha ha ha ha ha ha ha
Radšej my si mal zvái iné monosti...
Chceš kúpi mapu, hm?
Naše mapy sú prvotriednej kvality.  Nie sú to èmáranice, aké dostaneš od toho šaša cez ulicu.
Nie, iba artujem.
Vlastne, sú to kópie zápiskov z posledného zasadania PTA na ostrove Mêlée™.
Nemôem ich pusti z rúk.
Chceš jeden?
Nie, vïaka.
Nie, u musím ís.
Nie, ale vezmem si jeden, keï mi zaòho dáš dve zlatky.
Vidíš?  Hovoril som ti to.
OK, to je fér.
Máš rád potkany?
Áno, milujem potkany!
Nie, nemôem ich vystá.
Áno, hlavne v omáèke s bielym vínom.
Teraz o tom nemôem rozpráva.  Musím ís.
AIÉÉÉ!!!  Stra sa!!!
Frank, tento magor vydesil môjho potkana!
Oh, nie sú zase také zlé.
— zapišanie —
Vyzerá to, ako keby tento chlapec nemal rád potkany!
Zmláte ho!
Sú to ve¾mi inteligentné stvorenia!
Ha ha ha ha!!
Inteligentnejšie ako ON.
Poèul som príbeh o bande potkanov, ktorá priplávala z presláveného Ostrova opíc™.
Nie, tak to nebolo.
V skutoènosti to bola banda opíc.
To je ohromné!
ako sa tomu verí.
To je hlúpos, ako by mohla banda hlúpych opíc riadi loï!
Prepáète, musím ís.
Je to pravda.
Áno, ale je to pravda.
Vlastne, boli to šimpanzy, a NEBOLI hlúpe.
Keï priplávali, predali svoju loï za slušnı balík peòazí.
Aspoò raz som videl niekoho, kto urobil lepší obchod, ne Stan v jeho vrakovisku.
Myslel som si, e to boli potkany...
Nie, boli sme banda koèovnıch cirkusantov.
Ale tento potkan vydesil na smr slona.
Ale nejakı idiot vystrašil nášho cvièeného potkana.
Buï ticho!!
Samozrejme, e sme piráti!
Takéto handry nekúpiš nikde!
Èo chceš?
Èo je v tom súdku?
Prepáè, e som slovne obaoval tvojho potkana.
Kde ste zohnali takéhoto potkana?
Niè.  Uvidíme sa neskôr.
Preèo márnite èas na rohu ulice a nie ste na lodi, nekradnete, nevykorisujete a nedrancujete?
Rum.
Dem.
Dem.
Rum.
Er...  rum a dem.
Je to stará pirátska lahôdka, to vedia všetci.
No, pirátenie nám nejako nevyšlo...
Teraz sú tu a NADPRIRODZENE talentovaní piráti...
...prichádzajúci z Ostrova opíc™.
A tak sme boli donútení k inım alternatívam.
Skúšali sme rozbehnú cirkus.
Všetko fungovalo skvelo, ne ten potkan nevystrašil slona.
...a nejakı tupec nevystrašil aj nášho potkana!
Zdeprimoval si nás.
Choï domov.
Er...
No, áno, vieme o tom.
Preèo sa tu len tak flákate, miesto toho aby ste pre to nieèo u koneène urobili?
Idem po nehmotnıch únoscoch zastupite¾ov ostrova. Idete so mnou?
Môem vám ponúknu vysnenú dovolenku na Ostrove opíc™?
Vïaka neoèakávanım zmenám v zastupite¾stve ostrova
vám môem ponúknu celkom jedineènı a neopakovate¾nı zájazd do krajiny zázrakov na...
...Ostrov opíc™!
A to najlepšie na tom všetkom je práve tá cena:
Úplne zadarmo!
Všetko, èo musíte urobi, je sta sa posádkou na mojej lodi, a rajskı ostrov je váš...
ZADARMO!!
(...a pritom môeme zachráni aj guvernérku Marleyovú.)
Uh...
No...
Guvernérka sa urèite o seba postará sama...
...A máme tu ešte prácu...
- hej -
...a musíme premıš¾a o cirkuse...
...musíme nájs slona...
...nájs potkana...
HEJ!
...a zbavi sa tıchto zápiskov...
Prepáè, ale práve TERAZ nemôeme ís.
Urobíš najlepšie, keï odídeš, chlapèe.
Ha ha ha ha ha hoo hoo ha ha ha
Aak
Prepáète, ale nie—
Oh, to si zase ty.
Povedal som ti, e existuje iba JEDNA jediná.
Vrátil si sa pre mapu legendálneho strateného pokladu ostrova Mêlée™, však?
Dúfam, e tentoraz u máš dos peòazí.
Chcem len mapu.
Môj bratranec Sven vás pozdravuje.
Môeš mi poveda to heslo ešte raz?
Nevadí.  Kúpim si mapu niekde inde.
Nemáte pilník?
Chápem.
Chceš sa stavi?
Shhhhhhh!
Stíchni, hej?
Ten hnusnı šerif môe by niekde v okolí.
Teraz, môeš...
Prepáète, nemáte bratranca menom Sven?
Èo?
Nie, nemám.
Èo to má by?  Nejaké heslo?
Nie, ale raz som poznal kaderníka menom Dominik.
Nemáte pilníky?
Samozrejme, e to je heslo, idiot.
Dos blízko.
Nevadí.
Dobrú noc.
Všetky finanèné záznamy o Stanovej lodenici?
Osobné záznamy o šerifovom oddelení?
Actually, I meant the raspy metal kind.
Oh.
Hovorme o obchode.
Chceš si kúpi mapu legendárneho strateného pokladu ostrova Mêlée™?
Len jedinı na svete.
Vzácny.
Ve¾mi vzácny.
Iba 100 zlatiek...
Nie, vïaka.  Nemám dos peòazí.
Beriem to.  Bude to peknı darèek.
Nie, vïaka.  Nechcem to.
Tak a teraz sa stra, chlapèe, škodí to obchodu.
Tu máš.  Urobil si múdre rozhodnutie.
Teraz sa stra.
Nemáš dos peòazí, eh?
Vrá sa, a to budeš s h¾adaním pokladu myslie váne, chlapèe.
Hlboké.
Temné.
Zakázané.
Mmm.  Šavnaté banány!
To je èudné...
Je tu napísané `Morská opica`.
Vyzerajú, ako keby mali kadú chví¾u spadnú zo stromu.
Je ltı.
Je ltı.
Je ltı.
Stavím sa, e je odtia¾ vidie na celı ostrov.
Skvelé miesto so skvelım vıh¾adom.
Vyzerá ako bavlnená handra.
Nieko¾ko banánov spadlo na zem!
Bude lepšie to tu necha.
Bude lepšie to tu necha.
S veslami môem pádlova.
Nemám niè, s èím by som pádloval.
uuk
uuk
uuk
ííp
ííp
Ahoj!
Volám sa Herman Toothrot!
Neobauj sa pozdravovaním.
Èakám tu iba dvadsa rokov, aby som sa porozprával s niekım civilizovanım, mne to nevadí.
Dobre.
Keï sme pri tom, horí ti oheò pri zadku.
Mal by si to zahasi, ne sa niekto zraní.
`SPRÁVA MIESTNEHO ZASADANIA`
`Zasadanie sa uskutoèní v stredu veèer, a bude sa hovori o súèasnej okupácii Svätej Opièej hlavy hrôzostrašnım duchom piráta Lechucka...`
`...a následnom dopade na prostredie a turistickı ruch.`
`Všetci kanibali z celého Ostrova opíc™ sú srdeène vítaní.`
Sladko spia.
Asi sa cez ne nedostanem.
`Nechajme psíky vyspinka.`
Nechcem ich prebudi.
Blišie u nejdem!
DÔLEITÉ UPOZORNENIE
Tieto psy nie sú
màtve, oni len
SPIA
.
Poèas vıroby tejto hry
nebolo zranené
iadne zviera.
Draví pudli ryby nejedia.
Nemyslím, e sú vegetariáni.
Pochybujem, e to budú chcie.
Wuf.
Yip!
Je tu napísané: 'Porazil som Majsterku šermu'
Myslím, e by som sa mal o to stara ako v bavlnke.
Raz to môe ma ve¾kú hodnotu.
Hej!
Nemám rád návštevy!
Èo si zaè?
Ahoj, kapitán!
Èo vás sem priviedlo tak skoro?
Nemysleli ste si, e odtia¾ zdrhám, e nie?
Uh...
Nie, samozrejme e nie.
Len som vám chcel poveda, e...
...uh...
...mám loï...
...mám posádku...
...je všetko FAJN.
Hej, to je skvelé.
Take predpokladám, e sa uvidíme v prístave, však?
Správne...
Uvidíme sa tam.
No?
Našiel si nám kapitána?
No, vlastne nie.
Nehovor mi, e si prišiel, aby si mi znovu dokázal svoju statoènos.
Povedal som ti, e nie som iadny zbabelec.
Tak to ešte uvidíme!
Povedal som ti, nemám èas na to, aby som ti ukazoval ïalšie triky s tetovaním.
Predpokladám, e si vtrhol do môjho domu, aby si ma znovu uráal, však?
Pozri, povedal som ti...
iadne návštevy!
Guvernérka bola UNESENÁ!
Som Bobbin Threadbare.  Ty si moja matka?
Som pirát, ty lesklá gebu¾a.  Kto si ty?
Mohol by si mi znovu ukáza to tvoje skvelé tetovanie?
Aké e bolo to tvoje meno, lesklá gebu¾a?
Prepáète, ale na ceduli máte napísané, e prenajímate izby?
Hups!  Práve som zistil, e som v nesprávnom dome.
Nie, tvoja matka bola kaèka.
Tak u to nechaj.
Èo?  To je absurdné!
Oh, naozaj?
Pozri sa na ten list, èo tu nechali.
Pozri sa na ten list, èo tu nechali.
Oh nie.
To je strašné!
Èo budeme robi?
Uh... Dúfal som, e máš nejakı nápad.
Mohli by sme tu na nich poèka, kım sa nevrátia.
Mohli by sme zohna posádku a vypláva za nimi.
Prekonali sme nemoné a máme to vzda?
Hmmm...  Nechaj ma premıš¾a.
Hmmm...
No, to by šlo.
Ale bude to trochu nuda...
To je nápad!
No, je tu jedno riešenie...
Poèkaj!
U viem!
Zaobstaráme si loï s posádkou a vyplávame ju zachráni!
To je nápad!
Teda, pokia¾ u máme kapitána...
A èo ja?
TY?
HA HA HA HA!
To bolo dobré.
Hej, myslím to váne.
Fakt?
Naozaj.
Okej, tak mi to doká.
Prejdi sa tu.
No...
Dobre, ale ešte raz.
Pozri, povedal som ti, aby si ma tak nenazıval.
Volám sa Meathook...
...a ty máš stále problém s draním tela.
...a myslím si, e máš trochu problém s draním tela.
A ty máš stále problém s vlasmi.
No, a ty máš tak trochu problém s vlasmi.
Prepáè.  Nechcel som a nazva lesklou gebu¾ou.
To je dobré.
Radšej budem ma svoju lesklú gebu¾u, ne aby som mal konskı chvost.
Ha ha ha!
Ha ha ha.
Vlastne som a chcel nazva chrómovanou kupolou.
Hej, máš dobrı zmysel pre humor.
Chceš vidie nieèo fakt dos zábavné?
Asi radšej nie.
Ako èo?  Obrázok celej tvojej plešatej rodiny?
Áno, prosím, ukáte mi to, pán Meat.
Oh, no tak.
Bude to trva len sekundu.
Jeiši!
Nikdy nevieš kedy presta, èo?
To ani tvoj kaderník.
Prepáè.  Len sa pokúšam by zábavnı.
Chceš vidie nieèo zábavné?
Sleduj toto!
Povedz ahoj, Roger!
Ahoj, Roger.
Dos dobré, èo?
Dokáem toho ove¾a viac, ale teraz na to nemám vôbec èas...
Mono, keby sme sa ocitli na nejakej dlhej plavbe...
...ale do tej doby mám dos ve¾a práce, take...
Prepáè, ale ta cedu¾a tam vonku je u zastaralá.
Kedysi som tu mával prosperujúci turistickı podnik.
Mal som tu zvieracie predstavenia, ukáky tetovaní, suveníry...
Ale stala sa malá nehoda s jednım z trénovanıch zvierat...
...jeden z našich hostí bol dos nepekne zranenı.
Tak som to zavesil na klinec, a vykaš¾al sa na to.
A odvtedy ijem sám...
...a jediná spoloènos, ktorú mám, je rovnaká príšera, ktorá roztrhala nešastného turistu.
Tá istá príšera, ktorá zo mòa urobila invalida.
Príšera, ktorá je, zhodou okolností, identická s tou, ktorá ma napadla, keï som bol ešte diea...
...a nechala ma s tımito hákmi namiesto rúk...
...a zmrzaèeného.
Jeiši, teraz som úplne zdeprimovanı.
Fakt vïaka.
Mohol by si ma necha na chví¾u osamote?
Oh, okej.
Ui si to na ostrove Mêlée™!
Èo si...
Povedz zbohom, Roger.
Zbohom, Roger.
Ani sa to nehne.
Ani sa to nehne.
Ani sa to nehne.
Ani sa to nehne.
Ani sa to nehne.
Ani sa to nehne.
Choï a otvor to.
Je tu nieèo, èo by som ti rád ukázal.
...nieèo strašné.
Nieèo tak strašné, e keï na to pomyslím, tak celú noc nezaspím...
Ale nerád by som a vystrašil.
Som si istı, e ve¾kı a statoènı chlap ako ty nebude ma problém postavi sa tejto príšere.
Predsa len, je to ove¾a menšia obluda ako tá, èo mi pred mnohımi rokmi odhryzla ruky.
Len dúfajme, e si rıchlejší, ako som bol ja.
Oh, práve som si na nieèo spomenul...
Tento tıdeò som nemal dos èasu ju nakàmi.
Ja hlupák.
Ako si si samozrejme domyslel...
...bude ma ve¾kı hlad.
Nechám a, aby si otvoril posledné dvere.
Hlavne poèkaj, dokia¾ odtia¾ nevypadnem.
Poèkaj!
Skameneli ti nohy?
Nie, iba neviem, èo by som mal urobi.
Musíš otvori posledné dvere...
...a pokia¾ si dos statoènı,...
...dotkneš sa tej obludy.
Oh, to je všetko?
Okej.  Tak zaèni...
...zbabelec.
...ak máš odvahu.
Braaaak!
Neverím tomu.
Tak predsa si statoènı mu.
Postavil si sa príšere, ktorej som sa bal celé roky.
Mal si odvahu, ktorú som ja nikdy nemal.
Cítim sa ako zbabelec.
Nie som dos dobrı, aby som bol v tvojej posádke.
Nie som ani tak dobrı, aby som ti drhol palubu.
Oh, no tak, Meathook.
Oh, no tak, pán...
Meathook.
...pán Meathook.
Ste ve¾kı, silnı, dobré vyzerajúci chlap s hovoriacim tetovaním.
Ste ve¾kı, silnı, dobre vyzerajúci chlap so skvelım tetovaním—
Vie to hovori.  Chceš to vidie?
Uh, mono neskôr.
Mimochodom...
Palubu môeš drhnú, kedy sa ti zachce!
Fakt?
Iste.
Stále môem by v tvojej posádke?
Zba¾ si veci, a uvidíme sa v prístave.
Oh, ïakujem, ïakujem!
Nesklamem a.
Hej, mono e budem ma na mori šancu, aby som ti ukázal svoju zbierku tetovaní!
Vau, to zni èím ïalej tım lepšie.
Pokúšaš sa utiec, eh?
Myslím, e hej.
Zrejme si len ve¾kı slaboch.
Iba slaboch, stále slaboch.
Nie som slaboch!
Preèo nejdeš a nenájdeš pre našu posádku skutoèného kapitána?
Ja idem, ale nie som slaboch!
Uvidíš!
No iste.
Uhh...
Nemáte tu náhodou nejakı koreò, ktorı by som si mohol poièa?
Prišiel som vypoèu väzòa.
Prepáète, je toto paluba pre ¾udorútov?
Myslím, e u pobeím.
Zostanem radšej tu.
Ahoj, Karla.
Myslela som, e som ti povedala, aby si sa stratil.
Vlastne, som tu obchodne.
Tento chlapec za mnou prišiel do obchodu...
A èo ako, ty scvrknutı starı chlípnik...
...Vdy si vymyslíš nejakú vıhovorku, aby si sem prišiel a otravoval ma.
Nu, myslím, e hej.
Dobre, nechaj to tak.  Je mi z toho zle.
Upa¾uj spä a u sa sem nikdy nevracaj.
Niekto by a mohol sledova a potom sa zo mòa stane ïalšia turistická atrakcia otrova Mêlée™.
Hej, tvoja chyba, dievèatko.
Ten chlapec sa na teba stále pıta, Karla...
Pozri...
...ak sem prídeš ešte raz, odseknem ti hlavu a nap¾ujem ti do krku...
...chápeš?
Milujem, keï takto rozprávaš.
No, dobre.
A teraz ZMIZNI.
Tá èudná tekutina rozoiera dbán!
Chlapèe, musíš by unavenı.
Uuk
Uuk
Uf
Toto je druhá najväèšia opièia hlava, akú som kedy videl!
Fuj.
Ble.
Vau!
Takto to nepôjde.
Odtia¾to na to nedoèiahnem.
`SÚKROMNİ POZEMOK`
`Uctievanie je povolené, ale NEVSTUPUJTE, prosím, do Opièej hlavy.`
`— G.P. LeChuck`
Teploš keBob
Teploš keJoe
Teploš keLarry
Umelec si tu vytesal svoje meno:
`Vyrobené Èervenou lebkou.`
`Vyrobené Ostrozubom.`
Haló, pán navigátor.
Haló.
Nebudeš ma zase otravova kvôli náhrdelníku, však?
Okej, sme tu.
Take èo odo mòa chceš?
Áno?
Haló, hlava.
Mohol by som, prosím, dosta ten náhrdelník?
Vïaka, e si ma doviedol a sem.
Ešte raz ti ïakujem, e si ma doviedol a sem.
No, bolo mi potešením.  Teraz a dám naspä.
Haló.
Môem pre teba nieèo urobi?
Hej, iadny problém.
Je to to jediné, èo dokáem...
tak to robím poriadne.  Chápeš, nie?
Mám pocit, e sa ma chystáš o nieèo poiada.
Kde?
Do toho a niè nie je.
Áno, rozumiem.
Nie, ale vïaka, e si sa tak slušne spıtal.
Preèo mi to nedáš?
Oh, no tak, prooosííím?
Pekne prosím?
Pekne PEKNE prosím?
Pekne prosím s cukríèkom navrchu?
Mono si to len tak vezmem...
Nerád by som ti ublíil...
Èo mi urobíš?  Pohryzieš ma?
Keby som chcel, tak a kopnem do hlavy.
Fajn.  Zase tak ve¾a som toho nechcel.
Dobre, pretoe to nedostaneš.
Z tohto miesta mám èudnı pocit.
Mono ho budem potrebova.
Pozri, nebuï protivnı, okej?
Môeš obra ako chceš, ale nedostaneš to.
Oh, tak dobre, ty ve¾ké decko.
Vezmi si to.
To by som nerobil.
Nechcem, aby si to ¾utoval.
Mysli na to, e sa odtia¾ bezo mòa nedostaneš.
Keby som chcel, tak a tu môem necha naveky.
Na druhej strane...
Hej, na èo ti je náhrdelník, keï nemáš iadne ramená?
Hmm.  Dvere sú zamknuté.
Ahoy, cudzinec.
Novı v meste?
Hej, rád a zase vidím.
Uh-oh, vyzerá to, e mi dochádza grog, take ma na chví¾u ospravedlò.
Ako si to hovoril, e sa voláš?
Volám sa Guybrush Threepwood.  Práve som prišiel.
Si pirát?  Môem sa prida k tvojej posádke?
Kto tu velí?
Chcem sa rozpráva s vodcami pirátov.
Kde nájdem guvernérku?
Rád som sa s tebou porozprával.
No, ja som pirát.
Ale nie som kapitán.
No, tento ostrov má guvernérku...
...ale piráti majú vlastnıch vodcov.
Chcem sa rozpráva s vodcami pirátov.
Kde nájdem guvernérku tohto ostrova?
To je milé.  Dovidenia.
Prepáè.
Guybrush Threepwood?
Ha ha ha!!!
To je to najhlúpejšie meno, aké som kedy poèul!
No hej, ...to meno sa mi páèi.
No, a ako sa voláš?
Nu, trochú blbé meno, nie?
Urazil si ma.  Zbohom.
Ale veï to ani nie je meno!
Volám sa Mancomb Seepgood.
To je dobré.
Moje je Mancomb Seepgood.
Je mi ¾úto, e odchádzaš naštvanı.
Nehanbi sa.
Mal by si sa porozpráva s tımi dôleito vyzerajúcimi pirátmi vo ved¾ajšej miestnosti.
Oni tu tomu velia.
Povedia ti, kam ís a èo robi.
Guvernérka Marleyová?
Jej sídlo je na druhej strane mesta.
Ale piráti tam u nie sú vítaní.
Preèo nie?
Mòa ale vítajú všade, kam prídem.
Myslím, e tam pôjdem ihneï.  Dovi.
No, keï myslíš.
Hlavne si dávaj bacha na stránych psov!
Okej, ale dávaj si pozor na stránych psov!
No, naposledy pozvala jedného piráta na veèeru a on sa do nej zamiloval.
Tım sa to ostatnım tak trochu skomplikovalo.
Ako to?
Kto je ten pirát?
To je dos zlé.  No, uvidíme sa neskôr.
Nebol to nikto inı, ne hrôzostrašnı pirát LeChuck.
No, hovorí sa dos dlhı príbeh o tom, èo sa dialo ïalej...
Ale neverím tomu ani slovo.
Estevan, èo sedí tamto pri stole, ti mono povie viac.
Celú vec berie hrozne váne.
VE¼MI váne.
Tak èo a privádza na ostrov Mêlée™?
Chcem sa sta pirátom!
Prišiel som h¾ada šastie.
Naozaj neviem.
Do toho ti niè nie je.  Zbohom.
Oh, naozaj?
Oh, musíš, všake?
No, nebudeme to rozvádza.
Myslím, e budeš potrebova nejakú radu.
Tak mi prepáète, pán tajnostkár.
Bolo fajn sa s tebou porozpráva.
Ui si to tu na ostrove Mêlée™.
Vyzerá to, e mi dochádza grog, take ma na chví¾u ospravedlò.
Preèo na mòa tak èumíš?
Èo teraz?
Pozri sa, z celej tej záleitosti s LeChuckom som pekne roztrasenı.
Take, ak ma ospravedlníš...
Chcel by som sa predstavi... volám sa Guybrush.
Èo sa, preboha, stalo s LeChuckom a guvernérkou?
Povieš mi príbeh o LeChuckovi?
Poznali ste piráta, èo sa zamiloval do guvernérky?
Preèo nie sú piráti vítaní v sídle guvernérky?
Èo pod¾a teba znamená meno `LeChuck`?
Prepáète, ale h¾adám terè na šípky.
Kto mi tu naleje?
Èo sa vám stalo s okom?
Ospravedlòujem sa, e vyrušujem.  Dovidenia.
No, práve som si dával kontaktnú šošovku, keï—
Hej, poèkaj chví¾u!
Do toho ti niè nie je!
Terè na šípky?
U iadny nemáme.
Mali sme tu strašnú nehodu.
Alkohol a hádzanie nejde dokopy.
Naleje?
Musíš poèka, a si a kuchár všimne...
...ale to môe trva celı deò.
Nájdi si dbán a prekåzni do kuchyne.
Všetci to tak robíme.
Fakt, a èo?
LeChuck?
Kvôli LeChuckovi, tak pre to!
LeChuck?
On je ten, ktorı šiel ku guvernérke na veèeru a nechcel odís.
Zamiloval sa do nej, ale ona mu povedala, nech sa dá vypcha.
A tak šiel.
A potom sa zaèali dia naozaj hnusné veci.
Èo je tak desivé na tom LeChuckovi?
Ako sa zaèali dia hnusné veci?
Ako zomrel?
Znie to strašidelne.  No, musím ís.
LeChuck bol hrôzostrašnı pirát.
Pokúsil sa ohromi guvernérku tım, e odhalí tajomstvo Ostrova opíc™.
Ale prišla hrozná búrka, ktorá potopila jeho loï, a nikto nepreil.
Mysleli sme, e to je koniec hrôzostrašného piráta LeChucka.
Mılili sme sa.
Èo sa stalo potom?
Aké JE tajomstvo Ostrova opíc™?
Milujem ten príbeh.  Dobre, uvidíme sa neskôr.
To vie len LeChuck.
Ale to ešte nie je koniec—
Stále pláva vo vodách medzi nami a Ostrovom opíc™.
Jeho loï duchov šíri po mori bezbonı teror.
To preto sedíme tu a nepirátime.
Tak je.
Ajé.
Ajé, aj tebe.
Peknı klobúk.
Poviete mi nieèo o LOOME.
Jeiši, akı okatı predajnı trik.
Rád som sa s vami porozprával.
Myslíš tu najnovšiu dychberúcu fantasy adventúru od Lucasfilms, ktorú má na svedomí Brian Moriarty?
Je to skvelı príbeh plnı dobrodrustva s nádhernım hernım rozhraním...
...úasnı, vo vysokom rozlíšení, s 3D pozadiami...
...s prepracovanım hudobnım doprovodom a zvukovımi efektami.
Netreba zabudnú na detailné animácie a špeciálne efekty,
elegantné ovládanie postáv, objektov a kúzel.
Ale poèkaj, je toho ešte viac!
V Loome netreba niè vpisova, kresli mapy alebo spravova inventár.
A na rozdiel od mnohıch dnešnıch adventúr, je ¾ahká aj pre zaèiatoèníkov.
Táto hra dokonca získala ocenenie za najlepšiu grafiku v roku 1989!
Tak to skús!
Choï a kúp si Loom ešte dnes!
Prepáè, ale u niektorıch vlastností som sa nechal trochu unies.
Ajé.
Je to dos aké.  Urèite to je plné zlata a šperkov.
{string:global_32}
{string:global_32}
{string:global_32}
Aká trápna uráka!
Aká trápna uráka!
Aká trápna uráka!
HA!  S nièím lepším u prís nevieš?
HA!  S nièím lepším u prís nevieš?
HA!  S nièím lepším u prís nevieš?
O èo tu ide?
O èo tu ide?
O èo tu ide?
Práve si dokonèil školu šermu?
Práve si dokonèil školu šermu?
Práve si dokonèil školu šermu?
Urazím a, a ty môeš poui tú istú uráku na mòa!
Urazím a, a ty môeš poui tú istú uráku na mòa!
Urazím a, a ty môeš poui tú istú uráku na mòa!
To nie je fér, pouívaš uráky Majsterky meèa.
To nie je fér, pouívaš uráky Majsterky meèa.
To nie je fér, pouívaš uráky Majsterky meèa.
To nie je fér, pouívaš uráky Majsterky meèa.
{string:global_33}
{string:global_33}
{string:global_33}
Povedal som:
Povedal som:
Povedal som:
Vyzerá to ako švihadlo.
Škaredé.
Nevyzerá dobre.
Nemôem to vytiahnu.
Radšej dám ten náhrdelník spä.
Hmmm...
Nemyslím si, e sa tu dá nieèo zobra.
Vôbec.  Niè.
Je tam napísané:
`Kapitánov lodnı denník, 10. marca.`
`S dôstojníkom Hermanom Toothrotom h¾adáme u mesiac Ostrov opíc™. Stále bez úspechu.`
`Pokyny zakúpené na ostrove Mêlée boli v skutoènosti recept, a nie mapa, ako sme si mysleli.`
`Kapitánov lodnı denník, 12. marca.`
`Prial by som si, aby sa Toothrot u koneène vykúpal.`
`Kapitánov lodnı denník, 17. marca.`
`Èo by som dal za to, aby Toothrot u prestal chrápa.`
`Kapitánov lodnı denník, 23. marca.`
`Toothrot mi u zaèína liez na nervy! Je len otázka èasu, kedy sa doòho pustím.`
`Kapitánov lodnı denník, 2. apríla.`
`Na poèes nášho zmierenia navrhol Toothrot, e uvarí veèeru.`
`Kapitánov lodnı denník, 3. apríla.`
`Neviem, ako sme to dokázali, ale doplávali sme na Ostrov opíc™.`
`Obidvaja sme omdleli po veèernej polievke, ktorú varil Toothrot, a keï sme sa prebrali, èo bolo pre mòa záhadou, zistili sme, e sme pri Ostrove opíc™.`
`Kapitánov lodnı denník, 4. apríla.`
`S Toothrotom sme naplnili loïku potravinami a sme pripravení vyrazi na Ostrov opíc™.`
`Obaja sme skutoène vzrušení tım, e sme prví civilizovaní ¾udia, ktorí odhalia tajomstvo Ostrova opíc™.`
`Kapitánov lodnı denník, 5. apríla.`
`Musíme sa vráti na loï.  Toothrot si pred odjazdom zabudol odskoèi na záchod, u mi s tım lezie na nervy.`
`Zajtra vyplávame opä.`
To bol poslednı záznam.
Je to vytlaèené v záhlaví!
`Pre kanibalov Ostrova opíc™:`
`Prosím, nehıbte s tım.`
`Je to precízne vyváené.`
`—Herman Toothrot—`
`Pán Toothrot:`
`Rozoberte, prosím, tento nebezpeènı objekt.`
`Citrónová hlava na to zhodil kameò zo skaly, a skoro zranil osobu, ktorá práve vešala hojdaèku na banánovník na junej plái.`
`Citrónovı hlava opä zhodil kameò zo skaly a skoro potopil loï plávajúcu okolo.`
`—Kanibali`
`Pre ducha piráta LeChucka:`
`Musíme vás opä poiada, aby ste obmedzili vaše noèné aktivity v okolí svätej Opièej hlavy.`
`Obyèajní ¾udia sa pokúšajú spa!`
`Oh¾aduplne dodriavajte nízku hladinu hluku.`
`—Kanibali Ostrova opíc™`
`P.S.—`
`Videli sme, ako dole vediete enu so šatkou na oèiach!`
`Pre kanibalov Ostrova opíc™:`
`Naozaj mi nevadí vaše uctievanie pred vašou svätou Opièou hlavou, ktorá slúi ako môj domov a tajná operaèná základòa...`
`...ale zdrte sa ponechávania zvyškov po špinavıch obetnıch rituáloch na mojom prahu.`
`Tie vás prosím, aby ste NEVSTUPOVALI do Opièej hlavy.`
`—G.P. LeChuck`
`Pre ducha piráta LeChucka:`
`Musíme protestova proti 'zabaveniu' nášho voodoo protikoreòa.`
`Uvedomujeme si, e je to pre vašu posádku nebezpeèné, ale toto je kráde!`
`—Kanibali Ostrova opíc™`
`Pre Hermana—`
`Vráte, prosím, náš k¾úè k svätej Opièej hlave.`
`—Kanibali`
`Pre kanibalov—`
`Nehodlám vám ho da, vy pijavice, dovtedy, kım mi nevrátite môj zberaè banánov.`
`—H.T.`
`Pre Hermana Toothrota`
`Od právnych zástupcov, Kladiva, eliezka a ezla`
`aloba proti kmeòu kanibalov za zlomyselné vhodenie vesiel do priepasti.`
`Myslím, e tu máme prípad.`
`Môeme ich alova za psychickú újmu a za jasné nedodranie majetkovıch práv.`
INŠTRUKCIE, AKO SA DOSTA NA OSTROV OPÍC™!!!
Zohria hrniec na 450 stupòov
Prida následovné prísady:
1 škoricovú tyèinku
4 listy mäty
1 ¾udskú lebku (drvenú)
1 kvapku atramentu z chobotnice
0,5l èervenej opièej krvi
1 celé kurèa
3 unce síry
1 alebo viac následovnıch prísad:
vitamín B12, oxid zinoènatı,
slad, tmel, prípadne
prírodnú arómu.
Necha vari na malom ohni.
To staèí pre štyri osoby.
Èo odo mòa chceš, ty hnusnı tåk?
Èo odo mòa chceš, ty hnusnı tåk?
Èo odo mòa chceš, ty hnusnı tåk?
Zastavova piráta môe by zdraviu škodlivé.
Zastavova piráta môe by zdraviu škodlivé.
Zastavova piráta môe by zdraviu škodlivé.
Padaj mi z cesty, inak sa presekám sám!
Padaj mi z cesty, inak sa presekám sám!
Padaj mi z cesty, inak sa presekám sám!
Ajé, nech je to dos dôleité.
Ajé, nech je to dos dôleité.
Ajé, nech je to dos dôleité.
Dnes máme peknú noc, èo hovoríš?
Preèo rozprávate tak smiešne?
Tak si si všimol, e všetky tieto cesty vyzerajú tak nejako rovnako?
Volám sa Guybrush Threepwood.  Priprav sa na smr!
Nemali by ste náhodou pri sebe zopár zlatiek...
Prepáè, e som a rušil.  Pôjdem si po svojom.
Dúfam, e máš nieèo fakt dôleité, keï si ma zastavil?
Dúfam, e máš nieèo fakt dôleité, keï si ma zastavil?
Dúfam, e máš nieèo fakt dôleité, keï si ma zastavil?
Pirát Lingo!
Pirát Lingo!
Pirát Lingo!
To je ten, o ktorom sa všetci rozprávajú.
To je ten, o ktorom sa všetci rozprávajú.
To je ten, o ktorom sa všetci rozprávajú.
No tak Guybrush, nenapínaj.
No tak Guybrush, nenapínaj.
No tak Guybrush, nenapínaj.
No hej!  Keï to spomínaš, tak áno.
No hej!  Keï to spomínaš, tak áno.
No hej!  Keï to spomínaš, tak áno.
Je to ale len preto, e sme unavení.
Je to ale len preto, e sme unavení.
Je to ale len preto, e sme unavení.
...ktoré by ste mi mohli poièa?
Potrebujem si kúpi nejaké hašlerky.
To mi hovor.
To mi hovor.
To mi hovor.
Stra sa, zbabelec, skôr ne a rozsekám na kúsky.
Stra sa, zbabelec, skôr ne a rozsekám na kúsky.
Stra sa, zbabelec, skôr ne a rozsekám na kúsky.
Svoje peniaze nikomu nepoièiavam, hlavne nie takım tåkom, ako si ty.
Svoje peniaze nikomu nepoièiavam, hlavne nie takım tåkom, ako si ty.
Svoje peniaze nikomu nepoièiavam, hlavne nie takım tåkom, ako si ty.
Zaèiatky nie sú ¾ahké.  Mal by si ís a ukradnú to ako pravı pirát.
Zaèiatky nie sú ¾ahké.  Mal by si ís a ukradnú to ako pravı pirát.
Zaèiatky nie sú ¾ahké.  Mal by si ís a ukradnú to ako pravı pirát.
Práve som dal moju poslednú zlatku jednému pirátovi dole pri ceste.
Práve som dal moju poslednú zlatku jednému pirátovi dole pri ceste.
Práve som dal moju poslednú zlatku jednému pirátovi dole pri ceste.
Potreboval si kúpi hašlerky.
Potreboval si kúpi hašlerky.
Potreboval si kúpi hašlerky.
Škoda.
Škoda.
Škoda.
Dokázal som to!
Mám ten koreò!
Vau!
Pozri, on neartuje!
Tu to je!
Nie je to takı strachoput!
Tak rıchlo, ideme vari pivo z kvaseného koreòa.
Poèkaj tu.  Hneï sme spä.
Pekná opièka.
Mám ten koreò.
Nakoniec nie som takı strachoput.
Chcel by som a ma vypchatú doma.  To by bola krása.
Tu to je.
Jeden strek a ektoplazma zasiahne cie¾!
A ak ti nieèo zvıši, je to vıborné s vanilkovou zmrzlinou.
Ve¾a šastia.
Vïaka.
Medzitım...
LeChuck a jeho posádka vracajúca sa z Mêlée, dorazili na skryté miesto v podzemnıch riekach Ostrova opíc™ a zakotvili.
Kapitán, pane...
Zastavil som sa, aby som vám zagratuloval k úspešnému únosu.
Kapitán?
Kapitán?  Ste vporiadku?
NIKDY SOM SA NECÍTIL LEPŠIE!
A ako sa má nás väzeò?
Ah áno, väzeò.
Mali sme malı problém...
PROBLÉM!
Nerobte si starosti, pane...
...všetko je pod kontrolou.
Utiekla u nieko¾kokrát...
...ale teraz je zamknutá v podpalubí.
Nikto sa nedostane dovnútra ani von.
Pre tvoje dobro v to dúfam.
Po nieko¾koroènom plánovaní, ktoré bolo takmer znièené mojou smrou, si teraz nemôem dovoli ani tu najmenšiu chybu.
Postaráte sa o pána Threepwooda?
Guybrush Threepwood nebude problém.
Práve teraz je dvadsa stôp pod vodou...
...a je nafúknutı ako vykàmené prasa.
Jeho oèi vyierajú kraby.
Ryby hodujú na jeho prstoch.
Skoro si elám tam by a sledova to na vlastné oèi.
Ah...iste pane...
—yech—
...tım si buïte istı.
Choï a skontroluj koreò.
Uisti sa, e je poriadne zamknutı.
Ajé ajé, kapitán.
U si trièko dostal...
A èo chceš teraz?
Mono bude lepšie necha a tak.
Dobrı nápad.
Chcem a zase zosmiešni pri šermovaní.
Chcem, aby sme sa stali priate¾mi.
Guvernérka bola UNESENÁ!
Mono bude lepšie necha a tak.
Ha!
Nechala som a vyhra, pretoe u mi bolo zle z toho, ako si sem stále chodil.
Myslela som, e sa u nevrátiš.
Chcem, aby si odišiel a nechal ma tak.
Èo?  To je smiešne.
Èo je to?
Oh, nie.
To nie je dobré.  Vôbec nie.
Zháòam loï a posádku, aby som ju zachránil.
Hmmm...
Mám pocit, e to o¾utujem, ale rátaj so mnou.
Uvidíme sa v prístave.
Dobrı nápad.
AAAAAAJJJJJÉÉÉÉÉ!!!
AAAAAAJJJJJÉÉÉÉÉ!!!
Vïaka odhodlanému veleniu kapitána Freepa -er- Threepwooda, Morská opica koneène vyplávala.
Nezastrašená nedostatkom navigaènıch prístrojov i skúseností, zaèala posádka plánova svoju plavbu.
Je to buï ukáka nièotnosti ¾udstva...
...alebo je to brvno s nieko¾kımi kameòmi.
Ïalej to nejde.
Odtia¾to je skvelo vidie oceán...
...napravo sú nejaké trosky.
...a napravo je moja loï.
Tam, kde zvyèajne stála moja loï, teraz plávajú trosky!
Hej, odtia¾ vidím svoju loï!
Ehm, skôr kopu šrotu!
Na¾avo sú nejaké trosky...
Na¾avo je moja loï...
...a na plái napravo je banánovník.
Vidím na plái ve¾kı banánovník!
Vau, to je dung¾a!
Na plái na¾avo je ve¾kı banánovník.
Dung¾a je dos zarastená...
...jediné, èo vidím, je svorka zvierat, ktoré sa navzájom poierajú!
Hej, vidím nášho pozorovate¾a na ostrove Mêlée™!
Práve sa pozerá priamo na mòa!
Nieèo tu je, ale je tu tma.
Nedoèiahnem na to.
Vyzerá to ako pero na písanie.
Neviem, èo by som napísal.
Niè ma nenapadá.
Vyzerá to ako prázdna truhlica.
Vyzerá to ako stará pokladnica.
Je to elezná truhlica, a je dos aká.
Aha!  Kúsok papiera.
A pár škoricovıch tyèiniek.
Je prázdna.
Je to dos aké.
Ve¾mi pekná dubová skrinka.
Skrinka je u otvorená.
Vyzerá, e je pevne uzamknutá.
Ve¾mi aká elezná truhlica.
Stará zaprášená kniha.
Pozrieme sa, èo v nej je.
Prázdne.
Vyzerá to ako kapitánova zásuvka.
Vieèko od krabice cereálií, vyuité ako záloka.
Pekná!
To musel urobi Stan.
Na to bude èas neskôr.
Som prekliaty.
Myslím, e zaèínam ma morskú chorobu.
Je to dos zaseknuté.
Èo by som dal za peknı, ve¾kı, vodnı balón.
Pekná zástava.
Trasú sa mi kolená, len keï sa na òu pozriem.
Nie je tu kam nasypa pušnı prach.
To nebude fungova.
Nie je tu iadna rozbuška.
To nebude fungova.
Nemám záujem vystreli sa do mora.
Na to zabudni!  Po dopade na zem si rozbijem hlavu!
Hej! Kanón nevystrelil!
Na to, aby som tam liezol bezdôvodne, je to príliš nebezpeèné.
Déja vu!
Priviazané.
Taká zberba lenivıch vandrákov.
Èoe?
Niè.
Násilie asi nebude to správne...
...hoci by som sa cítil lepšie.
Èoe?
Niè.
Násilie asi nebude to správne...
...hoci by som sa cítil lepšie.
Èoe?
Niè.
Hmm, títo vandráci nikdy robi nebudú.
Toto situáciu nevyrieši.
Mám pocit, e mi ve¾mi nepomôu.
Vau!!!  Toto je super cena $59.95 + DPH
Na prechádzku je to príliš ïaleko, mimochodom, neviem pláva.
Tak najprv...
Chcel by som poveda, e som ve¾mi rád, e môem pracova s takou skvelou posádkou.
Plavba, ktorú máme pred sebou, nebude ¾ahká.
Máme skúsenosti, vıdr, a hlavne...
SME TÍM.
Najskôr by sme si mali rozdeli prácu.
Èoe to po nás chceš?
Napísal som zoznam.
'núti maka' je správne.
Nechápem, èo je také aké na zachraòovaní guvernérky.
Ona sa dokáe o seba postara sama.
No a ako sa tak pozerám...
máme SKVELÚ loï...
...no...
...nieèo ako loï máme.
Preèo si teda neodpoèinú, nepriviaza kormidlo a na chví¾u si ne¾ahnú.
Mohli by sme sa aspoò trochu opáli.
Keï o tom tak premıš¾am, v poslednom èase som bol trochu pod stresom.
Odpoèinok by bodol.
Potom je rozhodnuté...
...preplávame Karibik.
—hmhh—
Hej, pozrite...
...dostali sme sa na Ostrov opíc™
Daj nám vedie, a nájdeš guvernérku...
...máme tu pre òu jedno vo¾né miesto.
Tak toto mi ve¾mi nepomôe.
Pochopil si dobre.
Sú naniè.
Èoe?
Niè.
Hej, chlapi, èo sa deje?
Èo by som mal spravi pre to, aby ste mi pomohli?
Poèul som, e na Ostrove opíc™ je pekné poèasie.
Hej!  Našiel som mapu Ostrova opíc™.
Dávam vám vzbúrencom pä sekúnd na to, aby ste zaèali nieèo robi!
Myslím, e sa vrátim na loï a lepšie ju ukotvím.
Vzdaj to, Guybrush.
Peknı pokus, Guybrush, no bez úspechu.
Potom zaènem nakopáva zadky!
Prepáè Guybrush...
...slovo 'vılov' pre teba niè neznamená?
Chápem, kam tım mieriš, vïaka.
Vılov  1: ponori niekoho pod kormidlo lode, ako potrestanie alebo muèenie.
Chápem, kam tım mieriš, vïaka.
Er, prepáè Guybrush...
...stojíš mi v slnku.
No a?
Nu!
Tak?
Posvätná opièia boskos!
Ostrov opíc™.
To nie je darèek!
Je to malı k¾úèik s pekne vyrytou opièkou.
Je to malı k¾úèik s pekne vyrytou opièkou.
To nie je darèek!
Je to malı k¾úèik s pekne vyrytou opièkou.
Je to malı k¾úèik s pekne vyrytou opièkou.
Tento k¾úèik sem nepasuje.
Je to plné sraèiek. Dúfam, e to nebudem musie jes.
Vyzerá to ako vymletı lodnı hrniec.
U tam niè ïalšie dáva nebudem!
Nemám recept.  Nevedel by som, ako zaèa s varením polievky.
Len kvapku.
Umm...Toto bude vynikajúce.
To by malo staèi.
Našastie toho mám asi milión.
Milujem škoricu.
U je naèase sa toho zbavi.
U mám dos vlákna; Nechám to tak.
Ani náhodou!  Na tieto peniaze som tvrdo drel!
Tento lacnı kompas je príliš peknı na to, aby som ho vyhodil.
Táto zámorská literatúra sa dobre èíta; Nechám si ju.
U to je dos horúce.
Z tejto polievky niè nechcem.
Zaplatil som za to ve¾ké peniaze; Nechám si to.
Do èerta, je to horúce!
Pekné a horúce.
Do èerta, je to horúce!
Sú to len lekcie tanca.
Preèo by som mal spáli tak perfektné jedlo?
Hej, ako keby som sa chcel naozaj zabi.
Mono to budem potrebova neskôr.
Spálim ich všetky.
Toto sa len tak nezapáli.
Hmmmm...
Miloval som to ako diea.
Ako sa to pekne rozpúšalo na jazyku.
SUPER!
Vo vnútri je darèek.
Viac u nezjem, mám dojem, e prasknem.
Má to rovnakú ve¾kos ako moja hlava.
Nasadím si to len v nutnom prípade.
Preboha!
U to horí.
Nechcel by som to tu zapáli.
Hmmmm...
Miloval som to ako diea.
Ako sa to pekne rozpúšalo na jazyku.
Je mi zle.
Fsspt.
Grrfk.
Psspert.
Aaak.
Blfftp.
Vyzerá vıbušne.
Staré hrdzavé truhlice.
Všetky sú zhrdzavené.
Stará hrdzavá truhlica.
Je to hrdzavé.
Myslím, e to potrebuje väèšiu izbovú teplotu.
Nie som odborník, ale odhadujem z takej èervenej farby, ...
...e je to ve¾mi kvalitné víno.
Ah, peknı buket.
Sudy s pušnım prachom.
VAU! Pušnı prach!
Trochu si ho vezmem.
Vezmem si ho ešte trochu.
Zatia¾ ho mám dos.
VAU! Pušnı prach!
Trochu si ho vezmem.
Vezmem si ho ešte trochu.
Zatia¾ ho mám dos.
Je to ve¾kı kus špagátu.
Je to kus špagátu.
Je to malı kúsok špagátu.
Je to malièkú kúsok špagátu.
Je to nekoneène malı špagát.
Je to ve¾mi kvalitné víno.
Vezmem si ho.
Prázdne.
Stará pirátska truhlica.
Staré hrdzavé truhlice.
Všetky sú zhrdzavené.
Sú to staré prázdne sudy.
Sú prázdne.
Fuj!!!
Odpornı opièí smrad!!!
Celá loï smrdí ako spotené ponoky.
Nabudúce budem chcie najprv testovaciu plavbu.
Mám pocit, e toto funguje len v podzemí.
Èudne to páchne.
Teší ma!
Vedel som, e sa vrátiš!
Vedel som, e nebudeš schopnı dosta túto malú krásku zo svojej hlavy!
No tak.  Be a pozri sa na òu znovu!
Rád a zas vidím!
Vedel som, e sa vrátiš!
Všetci sa vracajú!
Vieš preèo sa vracajú?
Som Stan zo Stanovho bazáru ojazdenıch lodí.
...a postavím sa pokojne na hlavu, aby som s tebou uzavrel obchod.
Akı druh plavidla h¾adáš?
Ve¾ké?
Malé?
Rıchle?
Pomalé?
Chceš to, mám to.
A ak to nemám, tak to zoeniem.
Chcem ti urobi takú ponuku, s akou budeš spokojnı.
Pretoe ak nie si šastnı ty, nie som ani ja.
Ale JA VIEM, e máš dnes šastnı deò.
Ako to viem?
Len sa pozri na všetky tieto lode!
Pre kadého mám nieèo!
Poï a poobzeraj sa!
Tak èo ti ešte môem ukáza?
Povedz mi—
Na èo by si sa dnes rád pozrel?
Uká mi tú najlepšiu loï akú máš.
Uh... mohol by som vidie tú èervenú ešte raz?
Nieèo nie tak drahé, ale nie staré.
Uh... mohol by som vidie tú vikingskú ešte raz?
Naozaj nemám tak ve¾a peòazí.
Uh... mohol by som vidie tú lacnú ešte raz?
Tá modrá naleštená, èo stojí ved¾a tvojej kancelárie, vyzerá dobre.
Uh... ko¾ko chceš za tú tvoju?
Vlastne, rád by som o tom ešte porozmıš¾al.
Hej, je fajn spozna niekoho, kto vie oceni kvalitu.
Dostupná kvalita?
Hej, to je moje motto!
iadny strach!
Kadá loï, ktorú tu predávam, je vıhodná kúpa!
Ale ak h¾adáš skutoènı unikát...
Mám tú PRAVÚ loï pre teba!
Vedel som to!  Vedel!
Nemôeš na òu zabudnú, však e?
Iste, iste.
Zrejme si vzdelanı mu, ktorı chce urobi vzdelané rozhodnutie.
Iste!
iadny problém!
Samozrejme,
e nemám niè iné na práci, ne aha svoj zadok po dokoch sem a tam a ukazova chlapom ako si ty, znovu a znovu, rovnaké lode, ako je deò dlhı!
Preèo nie?  Mám na to celı deò!
Poï tadia¾.
Táto...
Táto loï je robená pre krá¾a!
Vlastne, hovoríme tu o pätnástich miestnostiach—v kadej z nich kozub.
Hovoríme tu o dvoch bazénoch—jeden vnútornı, a jeden vonkajší.
Hovoríme tu o toèiacej sa taneènej sále.
Hovoríme tu o lodnom koši.
Hovoríme tu o dvesto stôp dlhej oceánskej nádhere.
A to všetko za ve¾mi nízku cenu.
Hovorme o cene...
Tak tu je tá loï...
...ktorá celkom iste stojí za podrobnú prehliadku.
Vidím, e si nároènı druh chlapa.
Ale tie môem poveda, e pre teba znamená kvalita ve¾a.
Staèí sa pozrie, ako sa obliekaš.
Robustnı.  Ako tento miláèik.
Prišla z ïalekého severu...
...kde je more ne¾útostné, rovnako ako mui sú tam tvrdí a—
—hej, nie si náhodou odtia¾, e nie?
Vyaruje z teba taká severská energia...
Mimochodom, hovoríme tu o skutoènej kvalite...
Nemôeš z nej spusti oèi, však?
Tu je slávna `Morská opica.`
—Jediná loï, ktorá doplávala na Ostrov opíc™...
...a vrátila sa spä so ivımi na palube.
Alebo, mal by som poveda, nieèím.
Vieš, poslednımi vlastníkmi lode boli dvaja dobrodruní piráti.
Vyplávali, ako mnoho ïalších, aby našli legendárne tajomstvo Ostrova opíc™.
A, ako mnoho ïalších, sa navdy stratili.
Ich osud—záhada.
Rovnaká záhada, ako sa táto loï vrátila na ostrov Mêlée™ bez jediného mua na palube.
Hovorí sa, e sa vrátila riadená posádkou šimpanzov.
Šimpanzov?  V Karibiku nie sú iadni šimpanzi!
Oh, buï ticho.  Takto je tento príbeh zaujímavejší.
Tak èi tak, tento miláèik je teraz môj...
Teda, dokia¾ mi niekto nespraví vıhodnú ponuku.
ako sa udriava odstup od záhadnıch vecí, však?
Hovoril som ti, e nie je na predaj!
Jeiši, ty si ale nepríjemnı...
Ale hej!
Ja tie, mám pravdu?
Samozrejme, e nie je.
Je moja.
A nie je na predaj.
Èo INÉ ti môem ukáza?
Ko¾ko by si chcel minú?
Poïme sa bavi o peniazoch — TVOJICH peniazoch.
Ko¾ko by si dnes rád minul?
O akom cenovom rozpätí uvauješ?
Peniaze nie sú dôleité!
Vlastne, dúfal som, e dostanem jednu na úver.
Oh... nie viac ako 172 zlatiek.
Oh... nie viac ako 174 zlatiek.
Oh... nie viac ako tak asi sto zlatiek.
Vlastne, nemám iadne peniaze.
Všetko èo mám, je toto gumové kurèa.
Dostal som úver od obchodníka.  Berieš ho?
Keï tak nad tım premıš¾am, toto nie je loï pre mòa.
Tak to teda beriem.  Ko¾ko máš?
Prepáè, chlapèe.
iadne poièiavanie alebo prenajímanie.
Je to stará Stanova filozofia.
Ak máš prácu, obchodník v meste by ti mohol da nejakı úver.
V tom prípade by sme si mali pohovori.
Pokia¾ a, samozrejme, nenapadol nejakı inı spôsob financovania...?
iadne peniaze?
iadny problém!
Myslím, e sa musíme bavi o úplne inıch lodiach.
Vidím, e si sa dlhú dobu pohyboval mimo lodného priemyslu.
Som rád, e táto loï nemá uši, priate¾u.
Pretoe, keby mala, tak by a prefackala.
Pozri...
Toto je ve¾mi rozumne ocenená loï...
ale nie zas tak dobre rozumná.
Myslím si, e na túto transakciu nemáš dos hotovosti.
Máš NEJAKİ inı spôsob platenia...
Èo?
Pochybujem, e si si pre náš obchod priniesol dos hotovosti.
Nemáš náhodou k dispozícii INİ spôsob platenia?
Nie je to jedno z tıch gumenıch kurèiat s kladkou uprostred?
U jedno také mám.
Rád by som.
Skutoène rád.
NAOZAJ rád.
Ale nie za cenu, ktorá by ma zruinovala.
Mono by sa do tvojho finanèného rozsahu vošla iná loï.
Hej, samozrejme!
Tvoj úver sa vdy Stanovi hodí...
Nezáleí na tom, e si mal v minulosti problémy so splatením...
Rozvod...
Bankrot...
Chronické gamblerstvo...
Nie som tu od toho, aby som a súdil, e?
Pokia¾ ti ten obchodník verí tak, e ti dá zmenku do ruky...
...potom musíš by dôveryhodnı mu so stálym prijímom, však?
No... správne.
No iste, tomu rozumiem.
Na váhaní nie je niè zlé.
I keï ma tım zdriavaš.
Okej, ale na tú loï sa dnes príjde pozrie ešte ïalších pä chlapov.
Nepoèítaj s tım, e tu ešte bude, ak si to rozmyslíš.
Samozrejme, e nie je!
H¾adáš ove¾a väèšiu loï, to poznám.
Okej, ale poviem ti, mám takı pocit, e...
...dnes odídeš s novou loïou zo Stanovho bazáru ojazdenıch lodí!
Iste, iste.  Konèíme.
Nechcem, aby si sa cítil pod nátlakom, alebo tak, premıš¾aj o tom.
Maj sa.
Dal som ti u moju vizitku?
Tu je.
Najradšej by som ti pre istotu dal ešte jednu.
Nie, nie, nie.  Mám ich dos, naozaj.
Ako chceš.
A nezabudni moje meno:
STAN!!!
Bez obáv.  Nezabudnem.
Vïaka.
Zabudol som ti da vizitku.
...a tu je nieèo, aby si na mòa nezabudol.
Kompas?
Extra silnı magnetickı kompas—
S tvojím obrázkom...
To je pravda!
Vdy ukazuje priamo sem, take keï budeš chcie urobi dobrı obchod, tak vieš, kam ís!
A sa vrátiš, budem tu.
Ale nemôem ti zaruèi, e tu bude i niektorá z tıchto lodí!
Správne.
V tejto dobe idú na draèku!
Áno, pane...
ako tu nieèo udrím dlho.
On sa vráti.
Tak a teraz to trochu oprášime, ok?
Ve¾mi skoro mi budeš musie da vánu ponuku, vieš.
Ja viem, e ju chceš...
...ty vieš, e ju chceš...
...a tie vieš, e ju chcem preda za kadú cenu...
Budúci tıdeò dostanem novú zásielku lodí, take si ma dostal.
MUSÍM tohto miláèika preda, aj keby som mal na tom prerobi gate.
Len mi povedz, èo mám urobi pre to, aby si odplával s touto loïou ešte...
DNES?!
Je ti jasné, e takéto sa u dnes nerobia?
Chlapèe, môeš mi poveda pravdu.
Je to kvôli tej enuške, všake?
Bojíš sa, èo ti povie, a prídeš domov s novou loïou.
Nebuï takı slaboch! Hovor na rovinu.
Postav sa jej!
Bude a za to rešpektova.
A keï uvidí túto loï...
...bude a pre òu MILOVA.
Ver mi.
Nerozumiem tomu.  MYSLEL som si, e a zaujíma táto loï.
Nemám niè proti tomu, aby si si s òou urobil skúšobnú jazdu okolo prístavu, ale naša poisovòa by bola proti.
Som na tvojej strane, chlapèe.
Naozajstnı lakomec je len môj šéf.
Pozri, mono ti to nedošlo, ale toto je jedinı lodnı prístav na ostrove, kde si môeš kúpi loï.
Práve premıš¾am o úsporách na školné mojich detí.
Poïme sa porozpráva o doplnkoch.
Chcel by som ti da ponuku.
No, èo si myslíš o mojej cene?
Na to zabudni.  Aj tak tú loï nepotrebujem.
Doplnky?
Chceš sa bavi o doplnkoch?
Skvelé!  Táto KRÁSKA je prepchatá doplnkami!
Napríklad...
U som ti povedal o vyhrievanıch oknách?
U som ti povedal o nezásekovej kotve?
U som ti povedal o posilòovaèi kormidla?
U som ti povedal o koenıch poahoch?
U som ti povedal o uzlometri?
U som ti povedal o drevenom vıahu z debien od burgundského vína?
U som ti povedal o sedadlách z imitácie dreva?
Jeiš, Stan, to znie vynikajúco.
Myslím, e sa dokáem zaobís bez tej haraburdy.
Tak dos o doplnkoch.
A za tie prachy to stojí.
Preto je to u zahrnuté v cene!
Vedel som, e budeš posudzova veci z rovnakého uhla ako ja.
Okej, ale neobviòuj ma z toho, a narazíš do ¾adovca alebo tak.
Iste, vykašli sa na bezpeènos.
No, myslím, e to bez toho popláva...
...ako.
Hej, cestuješ na¾ahko, rozumiem tomu, iste.
Samozrejme, vzbura je hnusné slovo...
Páni, vie tvoja ena o tom, e si takı drgroš?
Hej, myslím, e toto JE ve¾kı ústupok, èo?
Okej, ale vravím ti:
Fúzonôky NENÁVIDIA imitáciu dreva.
Okej, kde sme to boli...
Ale poèkaj, je toho viac!
Skvelé!
How much?
I'd like to pay 2000 pieces of eight.
I'd still like to pay 2000.
How does 3000 pieces of eight sound?
Does 3000 sound any better now?
Okay, okay.  4000 pieces of eight.
Did I already say 4000 pieces of eight?
All right!  5000!  But that's my final offer!
5000!   And that's my FINAL final offer.
Actually, I'd like you to squirm a little more.
Sure.  Hey!
That's my job, isn't it?
That's still not enough money.
Inflation works in the other direction, you know.
Sure, I guess we can start out at the bottom.
I got all day.
That's a little bit more like it...
...but not much.
I think we're working in the wrong direction, here.
I know you can try harder than that.
TWO THOUSAND LOUSY PIECES OF EIGHT!?!
Three thousand pieces of eight!?!
Four thousand pieces of eight!?!
Five thousand pieces of eight?!?
You could sail this puppy away TODAY, for just 10000 pieces of eight.
How does that sound to you?
You could sail this puppy away TODAY, for just 9550 pieces of eight.
You could sail this puppy away TODAY, for just 9100 pieces of eight.
You could sail this puppy away TODAY, for just 8650 pieces of eight.
You could sail this puppy away TODAY, for just 8200 pieces of eight.
You could sail this puppy away TODAY, for just 7750 pieces of eight.
You could sail this puppy away TODAY, for just 7300 pieces of eight.
You could sail this puppy away TODAY, for just 6850 pieces of eight.
You could sail this puppy away TODAY, for just 9000 pieces of eight.
You could sail this puppy away TODAY, for just 8550 pieces of eight.
You could sail this puppy away TODAY, for just 8100 pieces of eight.
You could sail this puppy away TODAY, for just 7650 pieces of eight.
You could sail this puppy away TODAY, for just 7200 pieces of eight.
You could sail this puppy away TODAY, for just 6750 pieces of eight.
You could sail this puppy away TODAY, for just 6300 pieces of eight.
You could sail this puppy away TODAY, for just 5850 pieces of eight.
You could sail this puppy away TODAY, for just 8500 pieces of eight.
You could sail this puppy away TODAY, for just 8050 pieces of eight.
You could sail this puppy away TODAY, for just 7600 pieces of eight.
You could sail this puppy away TODAY, for just 7150 pieces of eight.
You could sail this puppy away TODAY, for just 6700 pieces of eight.
You could sail this puppy away TODAY, for just 6250 pieces of eight.
You could sail this puppy away TODAY, for just 5800 pieces of eight.
You could sail this puppy away TODAY, for just 5350 pieces of eight.
You could sail this puppy away TODAY, for just 8400 pieces of eight.
You could sail this puppy away TODAY, for just 7950 pieces of eight.
You could sail this puppy away TODAY, for just 7500 pieces of eight.
You could sail this puppy away TODAY, for just 7050 pieces of eight.
You could sail this puppy away TODAY, for just 6600 pieces of eight.
You could sail this puppy away TODAY, for just 6150 pieces of eight.
You could sail this puppy away TODAY, for just 5700 pieces of eight.
You could sail this puppy away TODAY, for just 5250 pieces of eight.
Fine.
Be that way.
See if I care.
Now, wait a second!
Don't go away mad.
I'm sure we can work something out.
Well, maybe you're right...
Sorry, Stan.  I'm outta here.
Of course I am.
Now, where were we?
Oh yeah.
Okay!  Okay!
It's killing me, but okay!
And I thought I was going to give my children Christmas presents this year...
Just take it out of here.
I'm GLAD to get rid of it.
Oh yeah, do you have that note from the storekeeper on you?
Thanks.
And here's something for you to remember me by.
A compass?
An extra strong magnetic compass—
With your picture on it...
That's right!
It always points directly back here, so if you're looking for a good deal, you know where to go!
I've got to run these numbers by my boss... ...he'll think I'm nuts, but I'll talk him into it.
You meet me at the dock with your crew.
I'll bring the ship and the papers.
I just want to say that I really feel like we got to know each other today.
I mean, I really felt some bonding here.
And I don't just say that to everybody!
It's been great doing business with you.
Really.
(Sucker.)
See you at the dock, and don't forget your crew.
All three of them.
Grog...
Diet Grog...
Cherry Grog...
Grog Classic...
Caffeine Free Grog...
...and Root Beer.
There must be a more honest way to get some spare change.
Pieces of eight are the preferred local currency.
Gee, I wish I could have bought this one.
Spiffy.
Gee, maybe I should have bought this one...
Cute, but small.
Gee, maybe I should have bought this one...
Looks like one of those well-engineered imports.
It may not look like much, but it's mine.
I'm surprised this one is still afloat.
Gee, maybe I should have bought this one...
...nah.
Ah, a fixer-upper.
Gee, maybe I should have bought this one...
Dull, dull, dull.
Gee, maybe I should have bought this one...
Now that's a nice-looking vessel.
STAN'S PREVIOUSLY OWNED VESSELS
`I won't shut up until I've made you a deal!'         -Stan
I'd better not.
`I sold a ship!  Can you believe it?
I'm off on a long vacation spending some poor sucker's money!  Arrivederci, baby!`
-Stan
WELCOME TO STAN'S PREVIOUSLY OWNED VESSELS!
I'm off searching the globe right now for the finest in previously-owned marine transportation.
Have a look around, I'll be right back!
-Stan
`When you set sail for good value, all winds blow towards Stan's!`
(WARNING:  Contains strong magnet which may interfere with other navigational equipment.)
I'm not sure, but I think it's pointing towards Mêlée Island™.
It's pointing towards Stan's.
It seems to be filled with some carbonated fluid.
He's big, ugly, mean, and about to hit me again.
Rumble
Rumble
Rumble
Hmpf.
Nothing.
I give up!  You win!
I give up!  You win!
UNCLE! UNCLE!
Yikes!  Nice move.
Where did my sword go?
Look behind you... a three headed monkey!
OK, you win.
OK, you win.
OK, you win.
Wow!  You're good enough to fight the Sword Master.
Wow!  You're good enough to fight the Sword Master.
Wow!  You're good enough to fight the Sword Master.
I give up!  You win!
I give up!  You win!
I give up!  You win!
`SLASHMASTER™ — When you want a sword as sharp as your wit.`
On those helpless dogs?
That's inhumane!
It's already closed.
`Davey Jones Lockers: The last word in theft-, fire-, and grog-resistant storage devices.`
It's locked.
It's locked.
It's locked.
This is a grog-resistant safe.
Says so right on it.
I don't think that will open it.
`Get a handle on your savings with GRIPMASTER handles.`
Don't you be messing with that!
Hey!  Get away from that!
BREATHMASTER™  — For the pirate who cares about first impressions.
Oooo!  That's refreshing!
`DIGMASTER™ — The only shovel for serious treasure- hunting enthusiasts.`
I, the good and honorable storekeeper do hereby take liability for the debts of the bearer of this note for any amount up to 5000 pieces of eight.
I'd better not touch it.
That storekeeper guy might bite my head off.
`Ring bell for service.`
Hey, where'd you go?
I hike halfway across the island to try and get you a reservation with the Sword Master—
—who, by the way, says you can go jump in the lake—
—and when I come back, you're gone!
See if I ever do you a favor again, ungrateful little shoplifter!
See if I ever do you a favor again!
I've got my eye on you, boy.
Steal anything and I break your legs.
Ahoy there, fancy pants.
Hmmm...
There's nothing in here but this note.
Hmmm...
It's empty.
Looking for a Sword Master, are you?
Looking for a little 'five-finger discount' it looks like to me!
See if I ever trust you again, devious little shoplifting weasel-boy!
I can't believe I almost fell for that again!
You, young man, are in dire need of a keelhauling!
It's not that expensive!
Why don't you just buy it, cheapskate?
You're hoping I'll have a heart attack with all this walking, is that it?
Ha!
Just keeps getting funnier and funnier, doesn't it?
Just get over here!
Ah-ha!
Caught you, you little thief!
Caught you again, you little rat!
Don't you ever learn?
Okay, cough up the dough.
Maybe you'd like to pay for that?
Maybe you'd like to pay for those?
What about it?
I want it.
How much is it?
I don't want it.
It never fails!
I step away from the counter for two seconds and some idiot's already ringing that stupid bell!
I should've known it'd be you again.
The Sword Master says you can jump in the lake, by the way.
Sorry, no refunds.
Sorry, no refunds.
No thanks.  I like my breath this way.
What's that for?
I'm not that stupid.
I didn't say you were.
Not out loud, at least.
We only take cash here.
Waddya want?
About this sword...
About this shovel...
I'm looking for the Sword Master of Mêlée Island™.
Now that I have this sword, who can I test it out on?
I'm interested in procuring a note of credit.
I could really use a breath mint.
I'd like some rat repellent, please.
Do you have files?
I think I'd just like to browse.
I think I'd just like to browse for now.
I already told you, it's 100 pieces of eight.
Did you bring enough money this time?
That's 100 pieces of eight.
Take it or leave it.
I'll take it.
I don't have enough money.
I don't want it.
Great.
Best 100 pieces of eight you ever spent.
Figures.
How else do you want to waste my time?
Same price as the last time you asked me:
75 pieces of eight.
Another would-be treasure hunter, eh?
That'll cost you 75 pieces of eight.
I'll take it.
75 pieces of eight?  I don't have that much.
I don't want it.
Great.
It'll pay for itself, believe me.
You'll dig up 75 pieces of eight in no time.
But hey, save some treasure for the rest of us, would ya?
Ha ha ha!
Then you'd better go put it back.
Is there something here maybe that you CAN afford?
Well if you're looking for a good fight...
We've got the best swordfighter in all the Caribbean right here on Mêlée Island™.
Of course, no one knows where her secret hideout is...
Look, I told you, she doesn't want to see you.
Maybe if you asked her again?
Yeah, like I'm going to fall for that one again!
Oh, please.
I won't steal anything this time, I promise.
Be right back.
Wait a second!
You sneaky, light-fingered little weasel...
You don't think I'm stupid enough to try the same trick three times in a row, do you?
You're really starting to tick me off.
The Sword Master of Mêlée Island™?
Hmmm...  I don't know...
Nobody knows the whereabouts of her secret hideout...
...nobody except me.
I'd have to go and ask her if it's okay to show you the way.
Hmmm...
I guess I could hike all the way over there...
...AGAIN.
...ONCE.
Be right back.
AND DON'T TOUCH ANYTHING!
I've got my eyes on you, weasel-boy!
Don't try anything!
And none of your old tricks!
I can't believe I'm doing this again!
I expect to be back in about five seconds.
AND DON'T TOUCH—
Ah, I'm tired of this crap.
Blah, blah, blah, eyes in the back of my head, blah, blah, blah...
...blah, blah, blah, wring your neck, blah, blah, blah...
...you know the story.
This is really getting boring.
You are, are you?
Got a job?
Got yourself a job finally, eh?
Yes, of course I do.
To be honest, sir, I am not employed.
All right.
I'll get one of my notes and we'll fill it out.
Let's see here...
What did you say your occupation was?
I'm a grog-swilling, foul-smelling pirate.
I'm waiting tables at the Scumm Bar.
I'm an acrobat with a traveling circus.
I clean ships over at Stan's used ship yard.
To be honest, sir, I'm between jobs.
Foul-smelling, yes...
Grog-swilling, maybe...
But a pirate?
Don't make me laugh.
Come back when you've got some tattoos or a pegleg or at least an eyepatch, for crying out loud.
...and I'm the Queen of England.
The cook over there waits all his own tables.
He likes to spit on all his customers personally.
Not only are you unemployed, you're a liar!
You're one of the Fettucini brothers?
Where's your silly accent?
And where're your silly slippers?
Come back when you've got a job in a credible business.
I haven't seen a clean ship over there in years.
You're either lying, or you're just a crummy worker.
Either way, I don't trust you.
I appreciate your honesty.
But I didn't get to be eighty-three by being no jackass.
No job, no credit.
Come see me when you land a job, and we'll talk.
Thank you for telling me that.
I respect your honesty.
But I didn't get to be eighty-three by being no jackass.
No job, no credit.
Come back when you've got one.
You're telling me!
Here take one...
...please.
Take a whole roll!
That'll be one piece of eight.
I got some, but they ain't free.
Hah!
I'll bet you would.
But I haven't got any.
Did you mean hanging files or nail files?
Yes.
Hanging files.
Nail files.
No, the metal kind you use to open locks with.
Ah.
Sorry, we're out of those.
What else do you want?
Hey, this ain't no boutique.
Don't take all day.
Okay, but don't put your lips on anything.
Whatever.
Okay.
Wake me up if you need anything.
Be my guest, fancy pants.
Got a special on shovels today...
Could you hurry up?
I was hoping to close early today.
If you're thinking about stealing something, think again.
Hurry up!
Come on!  Just buy something.
What do you think this is?  A museum?
I don't have all day.
Let's go, fancy-pants!
Don't think, just buy!
Did you just come in here to get out of the cold, or do you need something?
Are you waiting for me to fall asleep or something?
Can I help you?
Got a good deal on swords right now...
Looks mean and ugly.
Oh yeah?  Well so's your old lady.
How dare you approach the Sword Master without permission...
Which I surely didn't give you.
How dare you approach the Sword Master with—
Oh, it's you again.
I beg your pardon, I must talk to you.
My name is Guybrush Threepwood.  I've come to kill you.
Hi, I'm selling these fine leather jackets.
I'm back, and boy are you in trouble this time.
OK, I think I got it this time.
I return, fresh from a kill!
Hi, remember me?
I doubt that.
Everyone who comes here is prepared to fight.
Let's be honest: you're here to prove yourself to the Pirate Leaders, in hopes of one day being as immoral as they are.
Yep, nailed it right on the head... gee, you're smart.
But, as you have no sword...
...I doubt you're really serious.
I can tell by the sarcastic expression on your face that you've been fully trained by Captain Smirk.
I can also tell from the Mêlée Times' sports page that you haven't won a single fight.
This would be nothing more then a waste of my time.
I can also tell from the Mêlée Times' sports page that you've won only one fight.
Not nearly enough to waste my time.
I can also tell from the Mêlée Times' sports page that you've won only two fights.
Not nearly enough to waste my time.
Let's get this over with.
What was your final grade in Captain Smirk's sword fighting class?
Uh...
Grade?
Class?
You mean you came here to take on the Sword Master of Mêlée Island™...
...possibly the greatest sword fighter in the entire Caribbean...
...without a single lesson in the art of fencing?
Yep.
How did you expect to defend yourself?
Gee...
I dunno.
I see...
...obviously not with your razor-sharp wit.
I'd advise you to seek out Captain Smirk's and get some real training.
It would hardly be ethical, sporting, or even interesting to fight someone as unskilled as yourself.
So beat it.
I told you, I'm not going to fight you until you get some training.
Nothing like being honest.
Do you have one in size 3?
Of course you don't!
Because you're not really a jacket salesman!
I don't think that would be wise.
She looks like she's meditating.
Hi!
I think I'm going nuts.
I've got to hurry up and rescue the Governor and get off this island!
I'm here to rescue the Governor of Mêlée Island™.
I'm a mighty pirate.
Seen any big, ugly, scary, see-through pirates around here?
Is there anything good to eat on this island?
Take me to your leader.
Is it always this hot around here?
Well...I hope you're happy.
You can go back and brag to all your friends about how you beat the Sword Master.
You'll need proof...
Here, this should convince them.
I hope this teaches you a lesson.
Now SCRAM!
Captain Smirk's Big Body Pirate Gym
Prices:
Sword Training 30 Pieces o' eight
Cannon Firing 160 Pieces o' eight (balls extra)
Grappling Hook 130 Pieces o' eight (hook extra)
He's terrible and insensitive and about to hit me again.
They're both empty.
I can't get anything out of that mug.
It's not really much of a mug anymore.
I can't put anything in that mug!
That wouldn't hold this stuff!
That wouldn't hold this stuff!
The Legendary Lost Treasure of Mêlée Island™
This carefully reproduced piece of Mêlée Island™ history has delighted thousands of would-be pirates and their families for generations.
Remember, there are other pirates on this island,
SO GO EASY ON THE TREASURE.
Leave some for the next person.
Here lies treasure of such unimaginable wealth...
...well, you'll just have to dig it up to believe it.
(Paid for by the Mêlée Island™ Chamber of Commerce.)
Hmmm...
...looks like a big plus sign.
What could that possibly mean?
I'm not stupid enough to do that twice.
I think an actual shovel might be better.
`I found the Treasure of Mêlée Island™ and all I got was this stupid T-shirt!`
It doesn't fit.
Figures.
This shouldn't take too long.
Hours pass...
Hey!  I think I hit something!
Oh, boy!
It's a T-shirt!
Not my size, but a nice one nonetheless.
Well, I guess I should put all this dirt back now.
More hours pass...
STOP!!
You must pay a toll!
You can't pass until you pay the toll!
Stand aside, troll, I'm a mighty pirate.
Oh, please, can't I pass?
How much is the toll?
How much did you say the toll was?
Shouldn't you have eaten me by now?
Look behind you!  A mouse!
Oops, sorry.  I'll take the long way around.
Boy, do you sound like a wimp.
I don't like wimps.
I'm not falling for that!
Scuttle along, you scurvy sea slug!
I'm not hungry.
Hah!
You're no pirate!
Why, the town drunk could out-insult you on his back!
...and probably would.
Oh, yeah?
I can out-insult anybody, you brainless clay doppelganger!
Stick it in your ear, you great green garrulous grub!
I'll just go and find out.  Good day.
Yeah!
You know, you could stand a lesson or two if that's the best you can come up with.
Not me you can't, you equally brainless silly little puppet!
I once owned a dog that was smarter than you.
Take THAT and stick it in your repertoire!
Uh...
...errrr...
Which ear, cudgel-breath?
...heh...
What's so good about it?
Well, what have you got?
Some semi-rancid meat?
A stew pot?
A rubber chicken with a pulley in the middle?
Don't mess with me, troll, I'm a mighty pirate!
30 pieces of eight?
A hundred odd pieces of eight?
A piece of eight?
Nothing of consequence.
Never mind, I have to go now.
Fine.
Begone.
I want something that will attract attention, but have no real importance.
Construction paper jockey shorts?
A monkey leash with three collars?
A rubber chicken with a pulley in the middle?
My old moss-covered three-handled family credenza?
I'll try to find something like that.  Bye.
Don't be silly.
You have three chances to give me what I want.  Then...
...I eat ya!
Actually, it's more like a fabulous doorstop.
Looks sharp.
Rusty, but sharp.
Litterbugs.  Sharp, though.
VERY sharp.
Sharp and dangerous.
Heavy and sharp.
It's sharp.  I'd better be careful.
I can't reach it— I'm tied to this stupid idol!
I guess I'll be needing a sword.
This one will do.
Gee, I don't know how much longer I can hold my breath.
Hey, Nick, I just committed a felony!
Did it involve that big knife you've got there?
Yeah!
What should I do with it?
Get rid of it!
I'll throw it in the water!
No, don't do that!
Why not?  I need to ditch it!
It might wash up somewhere!
What do I care?
MY prints won't be on it!
I'm throwing it in!
...naaaah.  I might need it.
See you.
See you.
He's babbling to himself.
Filthy and without pants, as usual.
That might not be wise.
That might not be wise.
That might not be wise.
It's yellow.
It's yellow.
I don't want to get any closer to that thing.
It might be booby-trapped.
It looks big and empty.
It's already open.
In a primitive, yet effective way, it's locked.
I think I can go in there now.
Hmmm.  Some nice, juicy bananas!
I think they're having a serious discussion.
I think it wants me to go to the left.
I think it wants me to go to the right.
I think it wants me to go to the front.
I think it wants me to go to the back.
I think it's a little confused.
I don't think he'd work very well if I did.
I'd rather pick on someone my own size.
I'd rather pick on someone my own size.
It wouldn't be a good idea to take it off here.
He already has it on.
I think I'd better hang on to it.
It's slimy and goopy and it's around my neck.
It's slimy and goopy.
I don't think it would work very well if I did.
It wouldn't be a good idea to take this off here.
You can't have it.
It's mine.
I don't need it here—
No ghosts around.
I can't put it on now—I've got the head whipped out.
I don't want to touch it any more than I have to.
I don't want to touch it any more than I have to.
It wouldn't be a good idea to take this off here.
You can't have it.
It's mine.
I don't need it here—
No ghosts around.
I can't put it on now—I've got the head whipped out.
Why?  It's empty.
Why?  It's empty.
Why?  It's empty.
Why?  It's empty.
Why?  It's empty.
I can't see inside from here.
But I'll bet it's empty.
I can't see inside from here.
But I'll bet it's empty.
I think they're waiting for me to give them something.
Looks a little overripe, except for those nice, juicy bananas!
Nothing left but bad fruit.
All I want are these bananas.  The other fruit looks a little bit past its prime.
No thanks.  The rest is no good.
Is that a banana in your pocket, or are you just glad to see us?
You've got a lot of nerve stealing from the notorious Monkey Island™ cannibals!
You're cannibals?!
Well, yes.
Although, lately we've been trying to stay away from red meat.
Only for health reasons.
We're still as vicious as ever.
Especially with tourists who try to steal our stuff for souvenirs.
Well, what do you have to say for yourself?
Ah, the banana thief returns to the scene of the crime.
Maybe we should just eat him right now.
Do you have any idea how much cholesterol is in one of these things?
Now then, how did you break out of our hut and why did you come back?
Well, well, well.
You're quite the escape artist, aren't you?
I told you we should eat him.
How you get out is almost as much of a mystery as why you keep coming back.
The real mystery is why he's not simmering with carrots right now.
I don't know if this is getting boring for you, but it sure is for me.
What now?
Don't eat me!  I'm a mighty pirate!
Don't eat me!  I'll give you anything!
Oh, go ahead and eat me.  See if I care.
Look behind you!  A three-headed monkey!
That means his skin will be leathery and his meat tough and stringy.
You are of no use to us, nutritionally speaking, but...
Yeah, yeah.  We know.
Anything?
Hmmm...
Okay...
Hey, whatever you say!
Ha!
We're not going to fall for that old trick AGAIN.
Hey!
Do you really think we're that stupid?
I wouldn't push it if I were you.
I guess we'll eat you now.
Unless...
If you had some sort of offering for us...
...something that we could pass on to the Great Monkey...
We'll give you one more chance to trade something of yours for your freedom.
Well?
Ah, the key to the Great Monkey.
Thank you very much.
Why don't you hang on to that for now.
Ah, one of those newfangled magnetic compasses.
Too high-tech.
Yeah, give me a good old-fashioned disembodied head any day.
We couldn't take that.  You've already given us so much.
We appreciate the natural fibers, but no thanks.
A rubber chicken with a pulley in the middle?
No thanks.  We already got one of those.
Sorry, we already have PLENTY of those.
Ha!
Your currency means nothing to the Great Monkey!
Do you really think we want that after you've had your grubby paws all over it?
Thanks, but we already have one of our own.
I don't think the Great Monkey would like that.
We already got one of those.
Yuck.  No thanks.
Now what would the Great Monkey do with THAT?
Come on, you can do better than that.
Do you have anything of a more spiritual value?
That's hardly an artifact worthy of the Great Monkey.
Obviously you have nothing for us.
Hey, wow!
This is impressive!
LEMONHEAD!!!
Take a look at this.
Oooh, that's nice.
And it says, `Made by Lemonhead`...
...just like one of mine!
We should take this to the Great Monkey.
Yes, I agree.
We are very grateful to you for this fine gift.
If there's ever anything you need on Monkey Island™, just come see us.
You ain't going nowhere until you give us something.
Yep.  Still empty.
It's an empty hut.
This hut is VERY empty.
Boy, this is the emptiest hut I've ever seen.
No two ways about it—this hut's empty.
I'll bet if I looked up `empty` in the dictionary, there'd be a picture of this hut!
Have you come back to let us repay you for your fine gift?
Well, actually, there is something...
No thanks.  Generosity is it's own reward.  Bye.
Well, if there's ever anything you need from us, just let us know.
Thanks.
What a guy!
Tell us.  What is it?
I'm looking for somebody.
I need a ship.
Can you guys crew a ship?
Money.  I want money.
On second thought, you've already done so much...
How did you get here if you don't have a ship?
Well, this big rock fell out of the sky...
I see.  Say no more.
Well, I'm sorry, but we don't have a ship.
No, we stay away from sea travel.
It's just too hard to get all the vitamin C you need when you're on a ship for extended periods.
That's not exactly what we had in mind.
Is there anything ELSE we could do for you?
Here?
On Monkey Island™?
We're the only people living on Monkey Island™.
Well, the only civilized people.
That's okay. The people I'm looking for aren't living.
That's okay. The people I'm looking for aren't civilized.
Whoops.  Guess I came to the wrong island.  Excuse me.
I'm looking for 30 dead guys and one woman.
I don't think I want to hear any more about it.
Wait, maybe he's talking about those dead pirates.
Oh yeah.  THOSE guys.
Then you've seen the ghost pirate LeChuck and his cadaverous crew?
Those jerks have been bugging us for months!
Zooming around here in that creepy ghost ship of theirs...
...wailing and moaning until all hours of the morning...
...scaring away all the cruise ship business.
Normally, when we have problems with the undead,
we just cook up our standard potion of exorcism and be done with it.
So why don't you do that now?
What's in your standard potion of exorcism?
Give me the potion!  I'll use it on LeChuck!
Where are LeChuck and his crew hiding?
We can't.
Why not?
Well, the main ingredient of the potion is a very rare root...
...in fact, there's only one in existence.
We only use a little bit at a time, you see.
But LeChuck stole the whole thing!
Where is he hiding it?
How do I get to these catacombs?
What's in your standard potion of exorcism?
LeChuck came in here and stole your root?  What a cad!
I'm off to find LeChuck and get the root!
Oh, and I suppose stealing bananas is any better?
The Great Monkey himself is the gateway to the catacombs of the underworld.
He's in a place beneath this island...
...somewhere in a huge system of catacombs...
...a hellish place filled with the wailing of tortured souls trapped forever in the rock...
...where the walls bleed and the air is thick with the rancid smell of pure evil.
Tourists used to line up for hours to see it.
What happened?  Health department shut you down?
Can't you just go down there and kick him out?
And then LeChuck came and ruined everything, right?
Sounds neat.  Can I see it?
No, we lost the key.
It was stolen!
Well, we loaned it to a hermit who lives on the island.
And until that crusty old pantless weirdo brings it back, we're keeping his banana picker.
Sorry, but it's just not that easy.
Trying to find LeChuck could be very dangerous.
You'd never find your way through the catacombs without the—
Hey!
Ixnay on the Eadhay of the Avigatornay!
The what?
Nothing.
Nothing.
What's the Eadhay of the Avigatornay?
Why are you guys talking in pig Latin?
Oday ouyay avehay away apmay ofway ethay atacombscay?
Oh, come on.  Tell me.  I gave you the idol.
Orrysay.  Onay.
It is a very nice idol.
I see he is baffled by our native dialect.
Good.
We could at least tell him what the head does.
Well, it's a navigating tool—
It's a head.
It was once attached to a navigator.
We've kept it alive magically so we could take advantage of its innate sense of direction.
Getting through the catacombs without it is impossible.
But it's our only one, so you can't have it.
I guess we have nothing to offer you.
And after he gave us that nice idol, too...
Feel free to come to the Great Monkey and visit your idol any time.
So anyway, Lemonhead, what was that you were saying about tropical oils?
Well...
—ahem—
Excuse us but we're in the middle of a serious discussion.
I know, but I really need that navigator head thing.
I told you, we only have one.
We don't know how to get another one.
Sorry.
I told you, you can't have our head.
We don't know how to get another one.
All I want is my banana picker back.
But will they give it to me?
They want the Monkey Head key back FIRST.
THAT'LL be the day!
Don't you think they're being unreasonable?
It's not as though I'm asking for a lot.
A long walk, a brief row, and a short hike later...
It's the same rock I put there.
It looks like someone put this here on purpose.
It was enough trouble getting it over here.
I don't think I want it.
Wow!
Looked like it hit the big banana tree on the beach!
I bet the odds against that are incredible!
It came close, but I don't think it'll hit it again.
That shot was one in a zillion!
I'll just put it here.
There's already one there.
What would I want with a big rock?
Rubber tree!
Whoops...
Yikes!
I think I'm getting dizzy!
Overcome by the fumes and stench, Guybrush quickly loses consciousness.
Moments later the voodoo spell kicks in, turning the ship to an unknown heading and off on its mysterious voyage.
Days pass…
You know, LeChuck was a deviant, obnoxious, slithery,  creepy-crawly sort of a guy, but I'll say one thing for him...
What's that?
He sure looks nice exploding against the night sky.
Yes, it's very romantic.
Can I buy you a root beer?
Sure.
Actually, I'm a bit sick of root beer.
There's more at Stan's—
While I was in the machine over at Stan's—
Gosh, I hope Stan's OK...
I wish my crew could have seen this...
You know, I completely forgot about Herman Toothrot!
At least I learned something from all of this...
What's that?
How to deal with frustration, disappointment, and irritating cynicism.
How to deal with frustration, disappointment, and irritating cynicism.
It's not the size of the ship...
Never pay more than 20 bucks for a computer game.
That sounds like something my husband would say.
Yikes!
Yes, I've heard that one.
A what?
I don't know, I'm not sure why I said that.
You know, I can't shake the feeling that Guybrush was somehow  responsible for that big rock sinking the ship...
Yeah.
As soon as we find a way off this island we're going to  have ourselves a little chat with Mr. Threepwood...
Let's get out of this hut, first.
Now, I wonder where my pirate friend has got to.
I certainly hope he didn't leave without me...
Well, that was certainly easier than the trip TO Monkey Island™.
I wonder where Toothrot's gone to NOW?
Now I'll have to stop the wedding by myself!
I wish those guys hadn't been so excited about getting sunscreen.
Now I'll have to stop the wedding by myself!
Aaahhhhhh!
Mám tri zlatky.
Mám štyri zlatky.
