Úspechy
Skutoène chcete naèíta túto uloenú pozíciu?
Skutoène chcete prepísa túto uloenú pozíciu? Prídete tak o všetok pokrok v tejto uloenej pozícii.
Skutoène sa chcete vráti do hlavného menu?
Naspä
Autori klasickej edície
Pokraèova bez uloenia
Ovládanie
Vytvori novú uloenú pozíciu
Pokia¾ vidíte tento symbol, nevypínajte konzolu Xbox 360, ani nevyberajte pamäovú kartu.
Skonèi hru
Pri ukladaní nastala chyba
Pomocník a monosti
Ako hra hru
Tabu¾ka najlepších
Naèíta hru
Hra sa naèíta. Nevypínajte, prosím, vašu konzolu Xbox 360.
Ostrov opíc
Hlasitos hudby
Nebola zvolená iadna pamäová karta. Vyberte si, prosím, pamäovú kartu alebo monos pokraèova bez uloenia.
OK
Vyberte si, prosím, pamäovú kartu s aspoò %iKB vo¾ného miesta, inak nebudete môc na òu uklada dáta.
Skonèenie bez uloenia bude ma za následok, e prídete o neuloenı pokrok v hre.
Zopakova naèítanie
Pokraèova v hre
Uloená pozícia nebola na pamäovej karte nájdená. Chcete vytvori novú uloenú pozíciu alebo pokraèova bez uloenia?
Uloi hru
Uloená pozícia sa zdá by poškodená a nie je moné ju poui.
Prebieha ukladanie obsahu. Nevypínajte konzolu.
Vybra
Vybra pamäovú kartu
Nastavenia
Hlasitos zvukovıch efektov
Autori špeciálnej edície
Titulky
Hlasitos reèi
Áno
Nie ste prihlásení k úètu Xbox LIVE a nemáte iadny prístup k tabu¾ke najlepších.
Nevybrali ste iadnu platnú pamäovú kartu. Ak sa rozhodnete pokraèova, nebude moné uklada váš pokrok v hre.
Nemáte iadny aktívny hráèsky profil. Ukladanie a úspechy nebudú k dispozícii. Pre vytvorenie alebo naèítanie hráèskeho profilu, stlaète tlaèidlo Xbox Guide. Chcete pokraèova bez monosti uloenia a úspechov?
Zruši
Skonèi
Vıber jazyka
Automaticky uloi a skonèi
Skonèi bez uloenia
Nie
Tabu¾ka najlepších
ZAP.
VYP.
Hra novú hru
Pokraèova/Naèíta
Naspä do hernej kninice
Odomknú plnú hru
Stlaète tlaèidlo A, aby ste videli tabu¾ku najlepších
Èakajte, prosím, prijímajú sa dáta z Xbox LIVE
Celkovı poèet hráèov:
Priatelia
Celkovo
Moje skóre
Hodnotenie
Gamertag
Dokonèené
Zobrazi
Hráèska karta
Prázdne
Automatické uloenie:
Pozícia
Pozor - Nie je moné prepísa automatické uloenie
Prvá èas: Tri skúšky
Druhá èas: Cesta
Tretia èas: Pod Ostrovom opíc
Posledná èas: Finále
Hrací èas:
Dokonèenıch percent:
Odpoji sa z Xbox LIVE
Stlaète ŠTART
Drte stlaèené [Y] pre preskoèenie
Drte stlaèené [X] pre zobrazenie rady
Zatia¾ nie ste ohodnotení v tabu¾ke najlepších tejto hry.
Vaši priatelia zatia¾ nie sú ohodnotení v tabu¾ke najlepších tejto hry.
V tejto tabu¾ke najlepších zatia¾ nie sú iadne poloky.
poloky
poloka
Nie je moné uloi dáta na zvolenú pamäovú kartu.
Naèíta sa…
banán
banány
plá
zvonèek
ve¾kı nos
ve¾ká kamenná hlava
krvavé ruky
knihy
misa s ovocím
mozog
hašlerky
broúra
rozbité okno
kanibali
jaskyòa
chumáè oènıch bu¾v
lodenica
pes
dvere
oèná bu¾va
oèi
bájna soška
tvár
priate¾skí domorodci
diera
duchovskı k¾úè
repelent na hlodavce
hlava navigátora
hlavy
srdce
Herman Toothrot
chatrè
dung¾a
leták
LeChuck
pozorovate¾
kúzelná sódovka
Príruèka dobrıch mravov
strašne ve¾kı kameò
huba
náhrdelník na Guybrushovi
náhrdelník na navigátorovi
list
obraz
broúra
cesta
pirát
piráti
kameò
gumené kurèa
lopata
cedu¾a
odstraòovaè sponiek
obchodníkov záznam
balzam z peòa
váza
voskové pery
zlatka
zlatky
trièko zo 100% bavlny
priechod
cesta
sekera
banán
zberaè banánov
banány
sud
kôš
koše
plá
ve¾ké drevené dvere
èierna truhla
loï
loï
kosti
záloka
f¾aša
hromada kostí
krabica plná meèov
most
briga
rozbitá f¾aša
vizitka
skrinka
kábel
koláè
táborisko
kanón
kanónová gu¾a
hlaveò kanónu
kapitánova poste¾
kotol strachu
jaskyòa
cela
cereálie
kalich
truhla
truhly
kurèa
kurèatá
škoricové tyèinky
cirkusovı stan
Obèan Mêlée
paseka
kopec
hodiny
mas na smaenie
hrniec na varenie
màtvola
gauè
trhlina
skrinka
záves
priehrada
smrtiaci sekáèik
smrte¾ne draví pudli
smrte¾ne draví pudli
miska
dvere
dvere
dvere
vchod
zásuvka
opitı duch
vyschnuté koryto rieky
zaprášená kniha
vıchod
bájna soška
pero na písanie
kvalitné víno
ohnisko
ryba
horiaci papierik
podpery
lesná cesta
rázcestie
pevnos
veštkyòa
rozbuška
duch
duch kuraa
duch psa
duch pierka
duch strácu
duch prasaa
loï duchov
náradie duchov
ohromnı kus povrazu
gigantické opièie ucho
gigantická opièia hlava
slizká mas
iariaca truhlica
sídlo guvernérky
zúrivé strašidlo
automat na grog
strelnı prach
píla
hrs strelného prachu
k¾uèka
obesená màtvola
otvor
kopa kameòov
dom
Hubert
kus mäsa
soška
váni piráti
atrament
ostrov
Jolly Roger
f¾aša grogu
dung¾a
sudy
k¾úè
rebrík
LeChuck
páka
svetlá
zámka
pozorovate¾
pozorovate¾òa
uvo¾nená doska
šavnaté banány
magnetickı kompas
mapa
znaèka
zápis
zápis
Mui s nízkou morálnou úrovòou (piráti)
zápisky
opica
opièie pozostatky
opièia hlava
k¾úè k opièej hlave
Ostrov opíc
dbán
dbán
vzbúrená posádka
Norbert
nos
list
list pod kameòom
vonku
priechod
cesta
cesta k mólu
cesta do dungle
obrázok
kúsok papiera
zlatky
rastlina a peò
rastliny
doštièka
ståp
jazierko
plagát
hrniec
hrniec s omáèkou
primitívne umenie
väzeò
šnúra
boxovacie vrece
r
potkan
ultra-ostré nonice
oheò
ústie rieky
kameò
kameò a rastlina
kameò na liste
zmes z koreòa
povraz
povrazovı rebrík
loïka a veslá
loïka
hrdzavı nô
trezor
vrece piesku
paluba
pobreie
cedu¾a
lebka
lebky
spiaca posádka duchov
k¾úèik
ïalekoh¾ad
schody
socha
obchodník
ulica
peò
meè
Majsterka meèa
Majsterka meèa
stôl
slnko
totem
vyènievajúci kameò
mesto
stopa
strom
trol
truhla
truhly
trièko
tunel
nezdravo vyzerajúci mu
dedina
liany
voodoo èaèky
voodoo korálky lásky
voodoo koreò
útla malá soška
okno
X
ltı kvet
Otv/Otvor
Zav/Zavri
Daj/Daj
Zap/Zapnú
Vyp/Vypnú
Stl/Stlaè
ah/ahaj
Pou/Poui
Pre/Prezrie
Choï/Choï k
Vez/Vezmi
Hov/Hovor s
Udr/Udrie
Str/Strèi
Vysm/Vysmieva sa
Pošt/Poštekli
Pich/Pichnú
Uch/Uchopi
Zdr/Zdrapnú
Pok/Poklepa
Hlaï/Hladi
Ovl/Ovláda
Cí/Cíti
Hnev/Hneva sa
Ruš/Ruši
Strè/Strka
Pozr/Pozrie sa a potom uchopi
<REKLAMA>
Pri/Prija
Dost/Dosta
Hoï/Hoï
v
s
na
do
Hlboko v Karibiku
leí ostrov Mêlée
Dni plynú
Okamité opakovanie
Úï/Údi
Trh/Trhnú
Zíz/Zíza
Smrï/Smrdie
Le/Letie
Hni/Hni
Nakl/Naklada do soli
Pos/Posúva
Zdr/Zdra sa
mäso v omáèke
dusené mäso
mäso s korením
pilník
drviè
štılová konfekcia
ako ozbrojenı klaun
hodi
oheò
roh nosoroca
hrozivı nebezpeène vyzerajúci bizón
aká stolièka
cirkus
hypnotizova
vari
škrípajúce dvere
rozpúšajúci sa dbán
vraednı okrídlenı démon
hnusnı pirát
páchnuci pirát
krvilaènı pirát
špinavı prehnitı pirát
Krá¾ovstvo ojazdenıch lodí
zvláštny kameò
rieka
kondor
silná vetva
silnı peò
veslá
Otravuj
diera
správy
nieko¾ko správ
viac správ
kopa správ
hromada správ
strašne ve¾a správ
príliš ve¾a správ
cena
nieèo ako nosoroec
èervené tlaèidlo
hrozivı bizón
hlodavec
ïalší hlodavec
horda hlodavcov
aká stolièka
srandovnı malı chlapík
šerif
Zrazi
ryba v omáèke
dusená ryba
dusené mäso
kúsok povrazu
dbán na grog
skoro deravı dbán
cínová vata
hypnotizova
Po dlhej prechádzke, rıchlom veslovaní
a krátkom trmácaní...
spiaci draví pudli
Chcete prepísa predchádzajúce dáta hry Monkey Island?
Klasická edícia je k dispozícii len v angliètine.
Monosti zvuku
Monosti obrazu
Ukladá sa…
Kurzor
Štandardná akcia
Predvolená akcia
Rada
Preskoèi medziscény
Akcie
Inventár
Menu
Vıber dialógov
Otvori
Poui
Zdvihnú
Tlaèi
aha
Zavrie
Prezrie
Hovori s
Rıchlos titulkov (klasická)
Alebo
Klávesové skratky akcií
(klasická)
Prepínanie verzií hry
Da
Rozlíšenie
Celá obrazovka
Poui
Špeciálne efekty
Nastala chyba pri inicializácii zvukového zariadenia alebo nebolo nájdené.
Váš poèítaè nespåòa minimálne systémové poiadavky.
Grafická karta nespåòa poiadavky.
Procesor nespåòa poiadavky.
Aplikácia sa teraz ukonèí.
Kód:
kremeò
Blimp-Cam
okorenená omáèka
bratia Fettuciniovci
